In [1]:
import psycopg2
import pandas as pd

/home/lmoraes/miniconda3/envs/machineteaching/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

In [2]:
connection = psycopg2.connect(user = "machineteaching",
                                  password = "",
                                  host = "localhost",
#                                   port = "5432",
                                  database = "machineteaching")
connection.autocommit=True
cursor = connection.cursor()

In [3]:
create_table_query = '''CREATE TABLE EXPERIMENTS_STABILITY
    (EXPERIMENT_ID SERIAL PRIMARY KEY,
    DATASET TEXT NOT NULL,
    X REAL ARRAY NOT NULL,
    Y REAL ARRAY NOT NULL,
    VECTORIZER TEXT NOT NULL,
    IS_BINARY BOOLEAN NOT NULL,
    MIN_DF REAL NOT NULL,
    DISTANCE TEXT NOT NULL,
    K INTEGER NOT NULL,
    METHOD TEXT NOT NULL,
    MODEL  bytea NOT NULL,
    CLUSTERING_TIME INTEGER NOT NULL,
    COHERENCE_SAMPLES5 REAL ARRAY NOT NULL,
    COHERENCE_SAMPLES10 REAL ARRAY NOT NULL,
    COHERENCE_SAMPLES15 REAL ARRAY NOT NULL,
    COHERENCE_MED5 REAL NOT NULL,
    COHERENCE_MED10 REAL NOT NULL,
    COHERENCE_MED15 REAL NOT NULL,
    COHERENCE_STD5 REAL NOT NULL,
    COHERENCE_STD10 REAL NOT NULL,
    COHERENCE_STD15 REAL NOT NULL,
    COHERENCE_TIME REAL NOT NULL,
    COHERENCE_K5 INTEGER NOT NULL,
    COHERENCE_K10 INTEGER NOT NULL,
    COHERENCE_K15 INTEGER NOT NULL)
    '''

cursor.execute(create_table_query)
connection.commit()

In [4]:
cols = ['dataset', 'k', 'min_df', 'is_binary', 'vectorizer', 'method', 'distance', 'clustering_time', 'coherence_time']
select_query = '''SELECT %s FROM EXPERIMENTS_STABILITY''' % ", ".join(cols)
cursor.execute(select_query)
r = cursor.fetchall()
# print(r)

In [5]:
df = pd.DataFrame(r, columns=cols)

In [6]:
df['total_time'] = df.sum(axis=1)

In [7]:
df[(df['dataset'].str.contains('dataset'))].sort_values(['k','min_df', 'is_binary','vectorizer'])
#    & (df['vectorizer'] == 'TfidfVectorizer') & (df['is_binary'] == True) & (df['distance'] == 'euclidean')
# df

,dataset,k,min_df,is_binary,vectorizer,method,distance,clustering_time,coherence_time,total_time
29,dataset0,2,0.05,False,CountVectorizer,nmf,euclidean,0,0.023457,2.073457
30,dataset0,2,0.05,False,CountVectorizer,lda,euclidean,0,0.012981,2.062981
1587,dataset1,2,0.05,False,CountVectorizer,nmf,euclidean,0,0.033381,2.083381
1599,dataset1,2,0.05,False,CountVectorizer,lda,euclidean,0,0.013175,2.063175
3270,dataset2,2,0.05,False,CountVectorizer,nmf,euclidean,0,0.033350,2.083350
3282,dataset2,2,0.05,False,CountVectorizer,lda,euclidean,0,0.011714,2.061714
5125,dataset3,2,0.05,False,CountVectorizer,nmf,euclidean,0,0.032648,2.082648
5126,dataset3,2,0.05,False,CountVectorizer,lda,euclidean,0,0.013141,2.063141
6648,dataset4,2,0.05,False,CountVectorizer,nmf,euclidean,0,0.031143,2.081143
6812,dataset4,2,0.05,False,CountVectorizer,lda,euclidean,0,0.013102,2.063102
8331,dataset5,2,0.05,False,CountVectorizer,lda,euclidean,0,0.013055,2.063055
8498,dataset5,2,0.05,False,CountVectorizer,nmf,euclidean,0,0.029349,2.079349
10002,dataset6,2,0.05,False,CountVectorizer,lda,euclidean,0,0.013032,2.063032
10167,dataset6,2,0.05,False,CountVectorizer,nmf,euclidean,0,0.033932,2.083932
11835,dataset7,2,0.05,False,CountVectorizer,nmf,euclidean,0,0.029233,2.079233
11836,dataset7,2,0.05,False,CountVectorizer,lda,euclidean,0,0.011938,2.061938
13461,dataset8,2,0.05,False,CountVectorizer,lda,euclidean,0,0.013103,2.063103
13493,dataset8,2,0.05,False,CountVectorizer,nmf,euclidean,0,0.034000,2.084000
15000,dataset9,2,0.05,False,CountVectorizer,lda,euclidean,0,0.011736,2.061736
15167,dataset9,2,0.05,False,CountVectorizer,nmf,euclidean,0,0.029517,2.079517
1177,dataset0,2,0.05,False,NCutVectorizer,nmf,euclidean,0,0.008647,2.058647
1178,dataset0,2,0.05,False,NCutVectorizer,lda,euclidean,0,0.009108,2.059108
2873,dataset1,2,0.05,False,NCutVectorizer,nmf,euclidean,0,0.012464,2.062464
2874,dataset1,2,0.05,False,NCutVectorizer,lda,euclidean,0,0.004786,2.054786
4562,dataset2,2,0.05,False,NCutVectorizer,nmf,euclidean,0,0.009196,2.059196
4563,dataset2,2,0.05,False,NCutVectorizer,lda,euclidean,0,0.003928,2.053928
6243,dataset3,2,0.05,False,NCutVectorizer,nmf,euclidean,0,0.009892,2.059892
6244,dataset3,2,0.05,False,NCutVectorizer,lda,euclidean,0,0.009077,2.059077
7926,dataset4,2,0.05,False,NCutVectorizer,nmf,euclidean,0,0.009727,2.059727
7927,dataset4,2,0.05,False,NCutVectorizer,lda,euclidean,0,0.009012,2.059012
...,...,...,...,...,...,...,...,...,...,...
10117,dataset5,15,0.50,True,NCutVectorizer,nmf,euclidean,0,0.013473,16.513473
10118,dataset5,15,0.50,True,NCutVectorizer,lda,euclidean,0,0.002735,16.502735
11784,dataset6,15,0.50,True,NCutVectorizer,nmf,euclidean,0,0.014070,16.514070
11785,dataset6,15,0.50,True,NCutVectorizer,lda,euclidean,0,0.002742,16.502742
13443,dataset7,15,0.50,True,NCutVectorizer,nmf,euclidean,0,0.006372,16.506372
13444,dataset7,15,0.50,True,NCutVectorizer,lda,euclidean,0,0.001750,16.501750
15114,dataset8,15,0.50,True,NCutVectorizer,nmf,euclidean,0,0.008782,16.508782
15115,dataset8,15,0.50,True,NCutVectorizer,lda,euclidean,0,0.002758,16.502758
16770,dataset9,15,0.50,True,NCutVectorizer,nmf,euclidean,0,0.009452,16.509452
16771,dataset9,15,0.50,True,NCutVectorizer,lda,euclidean,0,0.002775,16.502775
1132,dataset0,15,0.50,True,TfidfVectorizer,nmf,euclidean,0,0.012545,16.512545
1133,dataset0,15,0.50,True,TfidfVectorizer,lda,euclidean,0,0.003708,16.503708
2828,dataset1,15,0.50,True,TfidfVectorizer,nmf,euclidean,0,0.024556,16.524556
2829,dataset1,15,0.50,True,TfidfVectorizer,lda,euclidean,0,0.002887,16.502887
4517,dataset2,15,0.50,True,TfidfVectorizer,nmf,euclidean,0,0.012277,16.512277
4518,dataset2,15,0.50,True,TfidfVectorizer,lda,euclidean,0,0.002820,16.502820
6194,dataset3,15,0.50,True,TfidfVectorizer,nmf,euclidean,0,0.012474,16.512474
6195,dataset3,15,0.50,True,TfidfVectorizer,lda,euclidean,0,0.002730,16.502730
7879,dataset4,15,0.50,True,TfidfVectorizer,nmf,euclidean,0,0.012067,16.512067
7880,dataset4,15,0.50,True,TfidfVectorizer,lda,euclidean,0,0.003781,16.503781
9560,dataset5,15,0.50,True,TfidfVectorizer,nmf,euclidean,0,0.012681,16.512681
9563,dataset5,15,0.50,True,TfidfVectorizer,lda,euclidean,0,0.003445,16.503445
11225,dataset6,15,0.50,True,TfidfVectorizer,nmf,euclidean,0,0.012134,16.512134
11226,dataset6,15,0.50,True,TfidfVectorizer,lda,euclidean,0,0.002755,16.502755
12904,dataset7,15,0.50,True,TfidfVectorizer,nmf,euclidean,0,0.013256,16.513256
12905,dataset7,15,0.50,True,TfidfVectorizer,lda,euclidean,0,0.002827,16.502827
14558,dataset8,15,0.50,True,TfidfVectorizer,nmf,euclidean,0,0.022831,16.522831
14559,dataset8,15,0.50,True,TfidfVectorizer,lda,euclidean,0,0.002709,16.502709
16227,dataset9,15,0.50,True,TfidfVectorizer,nmf,euclidean,0,0.015770,16.515770
16228,dataset9,15,0.50,True,TfidfVectorizer,lda,euclidean,0,0.003751,16.503751

In [293]:
# c5_df[['min_df', 'is_binary', 'vectorizer', 'method', 'distance', 'k']].drop_duplicates()

      min_df  is_binary       vectorizer method   distance   k
0       0.05       True  TfidfVectorizer    lda  euclidean  13
1       0.05       True  TfidfVectorizer    lda  euclidean  11
2       0.35       True   NCutVectorizer    nmf  euclidean   7
3       0.40       True  CountVectorizer    nmf  euclidean  13
4       0.50      False   NCutVectorizer    nmf  euclidean  12
5       0.45      False   NCutVectorizer    nmf  euclidean  15
6       0.50      False  CountVectorizer    nmf  euclidean  11
7       0.05       True  CountVectorizer    nmf  euclidean  15
8       0.20      False  CountVectorizer    nmf  euclidean  15
9       0.05       True  CountVectorizer    lda  euclidean  13
10      0.30       True  CountVectorizer    nmf  euclidean  12
11      0.25      False  CountVectorizer    nmf  euclidean  13
12      0.35      False   NCutVectorizer    lda  euclidean   9
13      0.50      False   NCutVectorizer    nmf  euclidean  13
14      0.50      False   NCutVectorizer    nmf  euclidean  15
15      0.50      False   NCutVectorizer    nmf  euclidean  14
16      0.30      False  TfidfVectorizer    nmf  euclidean  15
17      0.45      False   NCutVectorizer    nmf  euclidean  14
18      0.05       True   NCutVectorizer    lda  euclidean  14
19      0.20      False  TfidfVectorizer    nmf  euclidean  15
20      0.40      False  CountVectorizer    nmf  euclidean  13
21      0.15      False  CountVectorizer    nmf  euclidean  10
22      0.35      False  CountVectorizer    nmf  euclidean  14
23      0.50      False  TfidfVectorizer    nmf  euclidean  14
24      0.50      False  TfidfVectorizer    nmf  euclidean  15
25      0.35       True  CountVectorizer    nmf  euclidean   9
26      0.40       True   NCutVectorizer    nmf  euclidean   8
27      0.20       True  TfidfVectorizer    nmf  euclidean  14
28      0.45      False  CountVectorizer    nmf  euclidean  15
29      0.50      False  CountVectorizer    nmf  euclidean  12
...      ...        ...              ...    ...        ...  ..
1661    0.15      False   NCutVectorizer    lda  euclidean  13
1662    0.20       True   NCutVectorizer    lda  euclidean  14
1663    0.30       True  TfidfVectorizer    nmf  euclidean   2
1664    0.20       True  TfidfVectorizer    nmf  euclidean   2
1665    0.10       True   NCutVectorizer    lda  euclidean   2
1666    0.10      False  TfidfVectorizer    lda  euclidean   4
1667    0.05      False   NCutVectorizer    nmf  euclidean   4
1668    0.10      False   NCutVectorizer    lda  euclidean   5
1669    0.10      False   NCutVectorizer    nmf  euclidean   4
1670    0.15      False  TfidfVectorizer    lda  euclidean   3
1671    0.05      False   NCutVectorizer    lda  euclidean   9
1672    0.15       True  TfidfVectorizer    nmf  euclidean   2
1673    0.20       True  TfidfVectorizer    lda  euclidean   2
1674    0.15       True  TfidfVectorizer    lda  euclidean  14
1675    0.25       True  TfidfVectorizer    nmf  euclidean   2
1676    0.10      False   NCutVectorizer    nmf  euclidean   3
1677    0.20      False  TfidfVectorizer    lda  euclidean   4
1678    0.10       True   NCutVectorizer    lda  euclidean  13
1679    0.15       True  TfidfVectorizer    lda  euclidean  11
1680    0.10      False   NCutVectorizer    nmf  euclidean   2
1681    0.05      False  TfidfVectorizer    lda  euclidean   5
1682    0.05      False  TfidfVectorizer    lda  euclidean   8
1683    0.05      False   NCutVectorizer    lda  euclidean   6
1684    0.10      False  TfidfVectorizer    lda  euclidean   2
1685    0.05      False  TfidfVectorizer    lda  euclidean   2
1686    0.05      False   NCutVectorizer    lda  euclidean   7
1687    0.05      False  TfidfVectorizer    lda  euclidean   6
1688    0.05      False  TfidfVectorizer    lda  euclidean  15
1689    0.05      False  TfidfVectorizer    lda  euclidean  13
1690    0.20      False  TfidfVectorizer    lda  euclidean  13

[1624 rows x 6 columns]

In [299]:
drop_query = '''DROP TABLE EXPERIMENTS_SOLUTION CASCADE'''
cursor.execute(drop_query)
connection.commit()

In [295]:
create_results_table = '''CREATE TABLE EXPERIMENTS_SOLUTION_RESULT
    (EXPERIMENT_ID INTEGER REFERENCES EXPERIMENTS(EXPERIMENT_ID),
    GAP_K INTEGER NOT NULL,
    GAP_K2 INTEGER NOT NULL,
    SILHOUETTE_K INTEGER NOT NULL,
    SILHOUETTE_K2 INTEGER NOT NULL,
    COHERENCE_K5 INTEGER NOT NULL,
    COHERENCE_K2_5 INTEGER NOT NULL,
    COHERENCE_K10 INTEGER NOT NULL,
    COHERENCE_K2_10 INTEGER NOT NULL,
    COHERENCE_K15 INTEGER NOT NULL,
    COHERENCE_K2_15 INTEGER NOT NULL)
    '''

cursor.execute(create_results_table)
connection.commit()

In [296]:
alter_results_table = """ALTER TABLE EXPERIMENTS_SOLUTION_RESULT
 ADD CONSTRAINT UC_SOLUTION_RESULT UNIQUE (EXPERIMENT_ID)"""

cursor.execute(alter_results_table)
connection.commit()

In [30]:
# cols_result = ["gap_k", "gap_k2", "silhouette_k", "silhouette_k2", "coherence_k", "coherence_k2"]
# cols_result_sql = ["experiments_result.%s" % item for item in cols_result]
cols_experiment = ['experiment_id', 'k', 'dataset', 'min_df', 'is_binary', 'vectorizer', 'method', 'distance', 'coherence_med5', 'coherence_med10','coherence_med15']
cols_experiment_sql = ["EXPERIMENTS_STABILITY.%s" % item for item in cols_experiment]

select_query = '''SELECT %s FROM EXPERIMENTS_STABILITY where dataset like 'dataset%%' order by coherence_med5 desc, coherence_med15 desc, coherence_med10 desc  '''  % ", ".join(cols_experiment_sql)
# select_query = '''SELECT %s FROM EXPERIMENTS_STABILITY where dataset like 'dataset%%' order by coherence_med10 desc, coherence_med5 desc, coherence_med15 desc  '''  % ", ".join(cols_experiment_sql)
# select_query = '''SELECT %s FROM EXPERIMENTS_STABILITY where dataset like 'dataset%%' order by coherence_med15 desc, coherence_med5 desc, coherence_med10 desc  '''  % ", ".join(cols_experiment_sql)
cursor.execute(select_query)
r = cursor.fetchall()

In [31]:
c5_df = pd.DataFrame(r, columns=cols_experiment).dropna()

In [32]:
c5_df

,experiment_id,k,dataset,min_df,is_binary,vectorizer,method,distance,coherence_med5,coherence_med10,coherence_med15
11,6178,10,dataset3,0.05,True,NCutVectorizer,lda,euclidean,0.009950,-0.130145,-0.235746
12,7950,14,dataset4,0.10,False,NCutVectorizer,lda,euclidean,0.009950,-0.254308,-0.672025
13,14572,7,dataset8,0.05,True,NCutVectorizer,lda,euclidean,0.009950,-0.122830,-1.308660
14,6212,13,dataset3,0.05,False,NCutVectorizer,lda,euclidean,0.007469,0.007469,-0.331439
15,11362,12,dataset6,0.15,False,NCutVectorizer,lda,euclidean,0.006639,-0.047629,-0.663792
16,9534,8,dataset5,0.05,True,NCutVectorizer,lda,euclidean,0.006639,-0.307062,-1.048600
17,7778,12,dataset4,0.45,False,TfidfVectorizer,lda,euclidean,0.005974,-0.364337,-1.638310
18,8288,15,dataset4,0.40,False,NCutVectorizer,lda,euclidean,0.005808,-0.046629,-0.182594
19,16324,15,dataset9,0.10,True,NCutVectorizer,lda,euclidean,0.005689,-0.093200,-0.480662
20,6238,12,dataset3,0.10,True,NCutVectorizer,lda,euclidean,0.005689,-0.093200,-0.645488
21,9744,15,dataset5,0.20,False,NCutVectorizer,lda,euclidean,0.005360,-0.090076,-0.262668
22,10495,13,dataset6,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.148251,-0.381515
23,13855,13,dataset8,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.186211,-0.423334
24,8815,13,dataset5,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.166291,-0.443332
25,2095,13,dataset1,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.186211,-0.443332
26,12175,13,dataset7,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.230499,-0.443332
27,3775,13,dataset2,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.240773,-0.443332
28,5455,13,dataset3,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.240773,-0.443332
29,415,13,dataset0,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.240773,-0.443332
30,7135,13,dataset4,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.240773,-0.443332
31,15535,13,dataset9,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.240773,-0.443332
32,9962,12,dataset5,0.40,False,NCutVectorizer,lda,euclidean,0.005202,-0.194146,-0.945303
33,16732,9,dataset9,0.45,False,NCutVectorizer,lda,euclidean,0.005202,-0.177314,-0.997257
34,4872,15,dataset2,0.35,False,NCutVectorizer,lda,euclidean,0.005183,-0.068694,-0.988133
35,1506,12,dataset0,0.35,False,NCutVectorizer,lda,euclidean,0.005142,-0.090099,-0.962803
36,3172,5,dataset1,0.35,False,NCutVectorizer,lda,euclidean,0.005136,-0.075735,-0.996573
37,14640,13,dataset8,0.10,True,NCutVectorizer,lda,euclidean,0.005114,-0.225640,-0.497771
38,2816,9,dataset1,0.05,True,NCutVectorizer,lda,euclidean,0.005070,-0.312131,-0.273566
39,9548,15,dataset5,0.05,True,NCutVectorizer,lda,euclidean,0.005070,-0.056813,-0.439511
40,868,15,dataset0,0.30,True,TfidfVectorizer,lda,euclidean,0.005070,-0.054456,-0.449350
...,...,...,...,...,...,...,...,...,...,...,...
16770,10682,8,dataset6,0.05,False,TfidfVectorizer,lda,euclidean,-1.143830,-0.502841,-0.751778
16771,10694,14,dataset6,0.05,False,TfidfVectorizer,lda,euclidean,-1.143830,-0.749171,-0.889086
16772,16282,8,dataset9,0.05,False,NCutVectorizer,lda,euclidean,-1.179370,-0.647454,-0.511546
16773,2836,5,dataset1,0.05,False,NCutVectorizer,lda,euclidean,-1.243320,-2.145270,-1.867990
16774,9116,9,dataset5,0.15,False,TfidfVectorizer,lda,euclidean,-1.318020,-0.527539,-0.666581
16775,592,3,dataset0,0.05,False,TfidfVectorizer,lda,euclidean,-1.320840,-0.584269,-0.399673
16776,15722,8,dataset9,0.05,False,TfidfVectorizer,lda,euclidean,-1.320840,-0.584269,-0.656058
16777,12892,7,dataset7,0.05,True,NCutVectorizer,lda,euclidean,-1.323240,-0.651835,-0.498591
16778,7328,11,dataset4,0.05,False,TfidfVectorizer,lda,euclidean,-1.337630,-0.832142,-0.805054
16779,11246,10,dataset6,0.05,False,NCutVectorizer,lda,euclidean,-1.370810,-0.766404,-0.810372
16780,15736,15,dataset9,0.05,False,TfidfVectorizer,lda,euclidean,-1.494190,-2.018700,-1.732420
16781,8994,4,dataset5,0.05,False,TfidfVectorizer,lda,euclidean,-1.520390,-1.181200,-1.245380
16782,12350,2,dataset7,0.05,False,TfidfVectorizer,lda,euclidean,-1.528840,-1.437200,-1.259460
16783,14042,8,dataset8,0.05,False,TfidfVectorizer,lda,euclidean,-1.557880,-1.356540,-1.566580
16784,9002,8,dataset5,0.05,False,TfidfVectorizer,lda,euclidean,-1.597290,-0.773403,-0.979004
16785,9016,15,dataset5,0.05,False,TfidfVectorizer,lda,euclidean,-1.649270,-2.320230,-2.241920
16786,672,15,dataset0,0.10,False,TfidfVectorizer,lda,euclidean,-1.701720,-0.863143,-1.310660
16787,760,3,dataset0,0.20,False,TfidfVectorizer,lda,euclidean,-1.753730,-1.250600,-1.140230
16788,4510,2,dataset2,0.05,False,NCutVectorizer,lda,euclidean,-1.756260,-1.163410,-1.005020
16789,11218,10,dataset6,0.05,True,NCutVectorizer,lda,euclidean,-1.830580,-1.549420,-1.841350
16790,15682,2,dataset9,0.05,True,TfidfVectorizer,lda,euclidean,-1.882450,-1.802880,-1.917300
16791,3954,4,dataset2,0.05,False,TfidfVectorizer,lda,euclidean,-1.974730,-1.090740,-0.818166
16792,11208,5,dataset6,0.05,True,NCutVectorizer,lda,euclidean,-1.986150,-1.830350,-1.256210
16793,14600,7,dataset8,0.05,False,NCutVectorizer,lda,euclidean,-2.017500,-1.320570,-0.941224
16794,15764,15,dataset9,0.10,True,TfidfVectorizer,lda,euclidean,-2.041700,-0.677100,-0.999055
16795,2286,10,dataset1,0.05,False,TfidfVectorizer,lda,euclidean,-2.066620,-1.618520,-2.231890
16796,11266,6,dataset6,0.10,True,NCutVectorizer,lda,euclidean,-2.246390,-1.050740,-1.195110
16797,9524,3,dataset5,0.05,True,NCutVectorizer,lda,euclidean,-2.649060,-2.124970,-2.397270
16798,5638,6,dataset3,0.05,False,TfidfVectorizer,lda,euclidean,-2.850230,-1.924210,-1.642100
16799,14040,7,dataset8,0.05,False,TfidfVectorizer,lda,euclidean,-3.449040,-2.868100,-2.462440

In [29]:
c10_df

,experiment_id,k,dataset,min_df,is_binary,vectorizer,method,distance,coherence_med5,coherence_med10,coherence_med15
11,6178,10,dataset3,0.05,True,NCutVectorizer,lda,euclidean,0.009950,-0.130145,-0.235746
12,7950,14,dataset4,0.10,False,NCutVectorizer,lda,euclidean,0.009950,-0.254308,-0.672025
13,14572,7,dataset8,0.05,True,NCutVectorizer,lda,euclidean,0.009950,-0.122830,-1.308660
14,6212,13,dataset3,0.05,False,NCutVectorizer,lda,euclidean,0.007469,0.007469,-0.331439
15,11362,12,dataset6,0.15,False,NCutVectorizer,lda,euclidean,0.006639,-0.047629,-0.663792
16,9534,8,dataset5,0.05,True,NCutVectorizer,lda,euclidean,0.006639,-0.307062,-1.048600
17,7778,12,dataset4,0.45,False,TfidfVectorizer,lda,euclidean,0.005974,-0.364337,-1.638310
18,8288,15,dataset4,0.40,False,NCutVectorizer,lda,euclidean,0.005808,-0.046629,-0.182594
19,16324,15,dataset9,0.10,True,NCutVectorizer,lda,euclidean,0.005689,-0.093200,-0.480662
20,6238,12,dataset3,0.10,True,NCutVectorizer,lda,euclidean,0.005689,-0.093200,-0.645488
21,9744,15,dataset5,0.20,False,NCutVectorizer,lda,euclidean,0.005360,-0.090076,-0.262668
22,10495,13,dataset6,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.148251,-0.381515
23,13855,13,dataset8,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.186211,-0.423334
24,8815,13,dataset5,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.166291,-0.443332
25,2095,13,dataset1,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.186211,-0.443332
26,12175,13,dataset7,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.230499,-0.443332
27,3775,13,dataset2,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.240773,-0.443332
28,5455,13,dataset3,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.240773,-0.443332
29,415,13,dataset0,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.240773,-0.443332
30,7135,13,dataset4,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.240773,-0.443332
31,15535,13,dataset9,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.240773,-0.443332
32,9962,12,dataset5,0.40,False,NCutVectorizer,lda,euclidean,0.005202,-0.194146,-0.945303
33,16732,9,dataset9,0.45,False,NCutVectorizer,lda,euclidean,0.005202,-0.177314,-0.997257
34,4872,15,dataset2,0.35,False,NCutVectorizer,lda,euclidean,0.005183,-0.068694,-0.988133
35,1506,12,dataset0,0.35,False,NCutVectorizer,lda,euclidean,0.005142,-0.090099,-0.962803
36,3172,5,dataset1,0.35,False,NCutVectorizer,lda,euclidean,0.005136,-0.075735,-0.996573
37,14640,13,dataset8,0.10,True,NCutVectorizer,lda,euclidean,0.005114,-0.225640,-0.497771
38,2816,9,dataset1,0.05,True,NCutVectorizer,lda,euclidean,0.005070,-0.312131,-0.273566
39,9548,15,dataset5,0.05,True,NCutVectorizer,lda,euclidean,0.005070,-0.056813,-0.439511
40,868,15,dataset0,0.30,True,TfidfVectorizer,lda,euclidean,0.005070,-0.054456,-0.449350
...,...,...,...,...,...,...,...,...,...,...,...
16770,10682,8,dataset6,0.05,False,TfidfVectorizer,lda,euclidean,-1.143830,-0.502841,-0.751778
16771,10694,14,dataset6,0.05,False,TfidfVectorizer,lda,euclidean,-1.143830,-0.749171,-0.889086
16772,16282,8,dataset9,0.05,False,NCutVectorizer,lda,euclidean,-1.179370,-0.647454,-0.511546
16773,2836,5,dataset1,0.05,False,NCutVectorizer,lda,euclidean,-1.243320,-2.145270,-1.867990
16774,9116,9,dataset5,0.15,False,TfidfVectorizer,lda,euclidean,-1.318020,-0.527539,-0.666581
16775,592,3,dataset0,0.05,False,TfidfVectorizer,lda,euclidean,-1.320840,-0.584269,-0.399673
16776,15722,8,dataset9,0.05,False,TfidfVectorizer,lda,euclidean,-1.320840,-0.584269,-0.656058
16777,12892,7,dataset7,0.05,True,NCutVectorizer,lda,euclidean,-1.323240,-0.651835,-0.498591
16778,7328,11,dataset4,0.05,False,TfidfVectorizer,lda,euclidean,-1.337630,-0.832142,-0.805054
16779,11246,10,dataset6,0.05,False,NCutVectorizer,lda,euclidean,-1.370810,-0.766404,-0.810372
16780,15736,15,dataset9,0.05,False,TfidfVectorizer,lda,euclidean,-1.494190,-2.018700,-1.732420
16781,8994,4,dataset5,0.05,False,TfidfVectorizer,lda,euclidean,-1.520390,-1.181200,-1.245380
16782,12350,2,dataset7,0.05,False,TfidfVectorizer,lda,euclidean,-1.528840,-1.437200,-1.259460
16783,14042,8,dataset8,0.05,False,TfidfVectorizer,lda,euclidean,-1.557880,-1.356540,-1.566580
16784,9002,8,dataset5,0.05,False,TfidfVectorizer,lda,euclidean,-1.597290,-0.773403,-0.979004
16785,9016,15,dataset5,0.05,False,TfidfVectorizer,lda,euclidean,-1.649270,-2.320230,-2.241920
16786,672,15,dataset0,0.10,False,TfidfVectorizer,lda,euclidean,-1.701720,-0.863143,-1.310660
16787,760,3,dataset0,0.20,False,TfidfVectorizer,lda,euclidean,-1.753730,-1.250600,-1.140230
16788,4510,2,dataset2,0.05,False,NCutVectorizer,lda,euclidean,-1.756260,-1.163410,-1.005020
16789,11218,10,dataset6,0.05,True,NCutVectorizer,lda,euclidean,-1.830580,-1.549420,-1.841350
16790,15682,2,dataset9,0.05,True,TfidfVectorizer,lda,euclidean,-1.882450,-1.802880,-1.917300
16791,3954,4,dataset2,0.05,False,TfidfVectorizer,lda,euclidean,-1.974730,-1.090740,-0.818166
16792,11208,5,dataset6,0.05,True,NCutVectorizer,lda,euclidean,-1.986150,-1.830350,-1.256210
16793,14600,7,dataset8,0.05,False,NCutVectorizer,lda,euclidean,-2.017500,-1.320570,-0.941224
16794,15764,15,dataset9,0.10,True,TfidfVectorizer,lda,euclidean,-2.041700,-0.677100,-0.999055
16795,2286,10,dataset1,0.05,False,TfidfVectorizer,lda,euclidean,-2.066620,-1.618520,-2.231890
16796,11266,6,dataset6,0.10,True,NCutVectorizer,lda,euclidean,-2.246390,-1.050740,-1.195110
16797,9524,3,dataset5,0.05,True,NCutVectorizer,lda,euclidean,-2.649060,-2.124970,-2.397270
16798,5638,6,dataset3,0.05,False,TfidfVectorizer,lda,euclidean,-2.850230,-1.924210,-1.642100
16799,14040,7,dataset8,0.05,False,TfidfVectorizer,lda,euclidean,-3.449040,-2.868100,-2.462440

In [21]:
c15_df

,experiment_id,k,dataset,min_df,is_binary,vectorizer,method,distance,coherence_med5,coherence_med10,coherence_med15
0,15144,13,dataset9,0.05,True,CountVectorizer,lda,euclidean,0.004988,0.004988,0.004988
1,8424,13,dataset5,0.05,True,CountVectorizer,lda,euclidean,0.003328,0.003328,0.003328
2,11778,10,dataset7,0.05,True,CountVectorizer,lda,euclidean,0.002912,0.002912,0.002912
3,3440,13,dataset2,0.10,True,CountVectorizer,lda,euclidean,0.002497,0.002497,0.002497
4,14,8,dataset0,0.05,True,CountVectorizer,lda,euclidean,0.003328,0.003328,0.001665
5,10102,12,dataset6,0.05,True,CountVectorizer,lda,euclidean,0.001665,0.001665,-0.010445
6,8418,10,dataset5,0.05,True,CountVectorizer,lda,euclidean,0.002081,0.001332,-0.013532
7,12058,10,dataset7,0.30,True,CountVectorizer,lda,euclidean,0.001832,0.001457,-0.014226
8,6744,13,dataset4,0.05,True,CountVectorizer,lda,euclidean,0.002497,0.002497,-0.015455
9,6747,15,dataset4,0.05,True,CountVectorizer,nmf,euclidean,0.003328,0.003328,-0.016571
10,1707,15,dataset1,0.05,True,CountVectorizer,nmf,euclidean,0.003328,0.003328,-0.016571
11,3387,15,dataset2,0.05,True,CountVectorizer,nmf,euclidean,0.003328,0.003328,-0.016571
12,15147,15,dataset9,0.05,True,CountVectorizer,nmf,euclidean,0.003328,0.003328,-0.016571
13,5067,15,dataset3,0.05,True,CountVectorizer,nmf,euclidean,0.003328,0.003328,-0.016571
14,27,15,dataset0,0.05,True,CountVectorizer,nmf,euclidean,0.003328,0.003328,-0.016571
15,10107,15,dataset6,0.05,True,CountVectorizer,nmf,euclidean,0.003328,0.003328,-0.016571
16,13467,15,dataset8,0.05,True,CountVectorizer,nmf,euclidean,0.003328,0.003328,-0.016571
17,11787,15,dataset7,0.05,True,CountVectorizer,nmf,euclidean,0.003328,0.003328,-0.016571
18,8427,15,dataset5,0.05,True,CountVectorizer,nmf,euclidean,0.003328,0.003328,-0.016571
19,13463,13,dataset8,0.05,True,CountVectorizer,nmf,euclidean,0.002497,0.002497,-0.016571
20,3383,13,dataset2,0.05,True,CountVectorizer,nmf,euclidean,0.002497,0.002497,-0.016571
21,1703,13,dataset1,0.05,True,CountVectorizer,nmf,euclidean,0.002497,0.002497,-0.016571
22,6743,13,dataset4,0.05,True,CountVectorizer,nmf,euclidean,0.002497,0.002497,-0.016571
23,5063,13,dataset3,0.05,True,CountVectorizer,nmf,euclidean,0.002497,0.002497,-0.016571
24,15143,13,dataset9,0.05,True,CountVectorizer,nmf,euclidean,0.002497,0.002497,-0.016571
25,23,13,dataset0,0.05,True,CountVectorizer,nmf,euclidean,0.002497,0.002497,-0.016571
26,11783,13,dataset7,0.05,True,CountVectorizer,nmf,euclidean,0.002497,0.002497,-0.016571
27,10103,13,dataset6,0.05,True,CountVectorizer,nmf,euclidean,0.002497,0.002497,-0.016571
28,8423,13,dataset5,0.05,True,CountVectorizer,nmf,euclidean,0.002497,0.002497,-0.016571
29,5062,12,dataset3,0.05,True,CountVectorizer,lda,euclidean,0.002497,0.001998,-0.016571
...,...,...,...,...,...,...,...,...,...,...,...
16770,11166,12,dataset6,0.50,True,TfidfVectorizer,lda,euclidean,-0.039145,-0.216393,-2.146320
16771,1074,6,dataset0,0.50,True,TfidfVectorizer,lda,euclidean,-0.039145,-0.216393,-2.146320
16772,4436,7,dataset2,0.50,True,TfidfVectorizer,lda,euclidean,-0.039145,-0.216393,-2.146320
16773,6124,11,dataset3,0.50,True,TfidfVectorizer,lda,euclidean,-0.039145,-0.216393,-2.146320
16774,14530,14,dataset8,0.50,True,TfidfVectorizer,lda,euclidean,-0.039145,-0.216393,-2.146320
16775,2758,8,dataset1,0.50,True,TfidfVectorizer,lda,euclidean,-0.039145,-0.216393,-2.146320
16776,7796,7,dataset4,0.50,True,TfidfVectorizer,lda,euclidean,-0.039145,-0.216393,-2.146320
16777,1082,10,dataset0,0.50,True,TfidfVectorizer,lda,euclidean,-0.039145,-0.216393,-2.146320
16778,12836,7,dataset7,0.50,True,TfidfVectorizer,lda,euclidean,-0.039145,-0.216393,-2.146320
16779,12844,11,dataset7,0.50,True,TfidfVectorizer,lda,euclidean,-0.039145,-0.216393,-2.146320
16780,2756,7,dataset1,0.50,True,TfidfVectorizer,lda,euclidean,-0.039145,-0.216393,-2.146320
16781,14522,10,dataset8,0.50,True,TfidfVectorizer,lda,euclidean,-0.039145,-0.216393,-2.146320
16782,9486,12,dataset5,0.50,True,TfidfVectorizer,lda,euclidean,-0.039145,-0.216393,-2.146320
16783,7836,13,dataset4,0.50,False,TfidfVectorizer,lda,euclidean,-0.054707,-0.132769,-2.146320
16784,6156,13,dataset3,0.50,False,TfidfVectorizer,lda,euclidean,-0.054707,-0.138792,-2.146320
16785,4446,12,dataset2,0.50,True,TfidfVectorizer,lda,euclidean,-0.035869,-0.247793,-2.155500
16786,8976,9,dataset5,0.05,True,TfidfVectorizer,lda,euclidean,-0.676735,-1.586750,-2.166700
16787,11190,10,dataset6,0.50,False,TfidfVectorizer,lda,euclidean,-0.016810,-0.574201,-2.221960
16788,2286,10,dataset1,0.05,False,TfidfVectorizer,lda,euclidean,-2.066620,-1.618520,-2.231890
16789,9016,15,dataset5,0.05,False,TfidfVectorizer,lda,euclidean,-1.649270,-2.320230,-2.241920
16790,556,13,dataset0,0.50,False,CountVectorizer,lda,euclidean,0.001249,-0.584269,-2.267860
16791,9518,14,dataset5,0.50,False,TfidfVectorizer,lda,euclidean,-0.037975,-0.643190,-2.278230
16792,4422,14,dataset2,0.45,False,TfidfVectorizer,lda,euclidean,0.002497,-1.015630,-2.297610
16793,4478,14,dataset2,0.50,False,TfidfVectorizer,lda,euclidean,-0.037087,-1.015630,-2.297610
16794,15070,4,dataset8,0.50,True,NCutVectorizer,lda,euclidean,0.001665,-0.277620,-2.332520
16795,9524,3,dataset5,0.05,True,NCutVectorizer,lda,euclidean,-2.649060,-2.124970,-2.397270
16796,14552,11,dataset8,0.50,False,TfidfVectorizer,lda,euclidean,-0.038907,-0.665508,-2.448800
16797,14040,7,dataset8,0.05,False,TfidfVectorizer,lda,euclidean,-3.449040,-2.868100,-2.462440
16798,9492,15,dataset5,0.50,True,TfidfVectorizer,lda,euclidean,-0.029308,-0.329757,-2.469410
16799,16252,7,dataset9,0.05,True,NCutVectorizer,lda,euclidean,NaN,-2.714230,-2.586670

In [43]:
c5_df[c5_df['experiment_id'] == 8424]

,experiment_id,k,dataset,min_df,is_binary,vectorizer,method,distance,coherence_med5,coherence_med10,coherence_med15
153,8424,13,dataset5,0.05,True,CountVectorizer,lda,euclidean,0.003328,0.003328,0.003328

In [62]:
import math
from itertools import combinations
TOP = 0.04
total = c5_df.shape[0]
rows = math.ceil(total * TOP)
print(rows)
ids = {}
# ids['sil'] = set(sil_df['experiment_id'].head(rows).values.tolist())
ids['c5'] = set(c5_df['experiment_id'].head(rows).values.tolist())
ids['c10'] = set(c10_df['experiment_id'].head(rows).values.tolist())
ids['c15'] = set(c15_df['experiment_id'].head(rows).values.tolist())
# print(len(ids['sil']))
combs = combinations(ids.keys(), 2)
for comb in combs:
    print("Merge set for %s and %s" % comb)
    merge_ids = ids[comb[0]] & ids[comb[1]]
    print("Size: %d" % len(merge_ids))
    print("Ids: %s" % merge_ids)
    print()
    
combs = combinations(ids.keys(), 3)
for comb in combs:
    print("Merge set for %s, %s and %s" % comb)
    merge_ids = ids[comb[0]] & ids[comb[1]] & ids[comb[2]]
    print("Size: %d" % len(merge_ids))
    print("Ids: %s" % merge_ids)
    print()

672
Merge set for c5 and c10
Size: 672
Ids: {10241, 10245, 10247, 6157, 14, 6159, 4113, 19, 2069, 21, 16407, 12311, 23, 12313, 27, 25, 10270, 6177, 6178, 10274, 6180, 6179, 6182, 6183, 4135, 6185, 6186, 6187, 6181, 4141, 2095, 4143, 47, 51, 55, 12343, 12345, 12347, 10301, 10303, 6210, 6212, 2123, 16461, 8270, 16463, 81, 12373, 6238, 8287, 8288, 16483, 16487, 107, 10355, 6271, 2183, 136, 10381, 12431, 8337, 8339, 157, 4255, 161, 165, 167, 6322, 2231, 6327, 2233, 188, 10431, 16575, 8391, 8393, 2265, 2267, 14557, 221, 223, 14559, 12513, 8419, 10469, 8421, 8423, 8424, 8425, 8427, 14572, 6381, 6383, 14576, 6384, 14577, 14579, 14581, 2293, 14583, 12535, 14585, 14587, 12541, 10495, 12543, 8447, 6403, 8451, 8455, 6407, 275, 277, 10523, 14620, 8481, 16684, 301, 16687, 14640, 2351, 8507, 14671, 10583, 8536, 16732, 351, 6495, 16737, 16739, 8557, 12655, 8561, 8565, 8567, 4477, 4479, 2433, 389, 4486, 10631, 14727, 10633, 14732, 4494, 4497, 4499, 10644, 4501, 16791, 4503, 16793, 4505, 4507, 2455, 2461, 415, 2463, 10665, 10667, 8621, 8623, 4530, 443, 14781, 14783, 10692, 10693, 4552, 6607, 14803, 4564, 14807, 2526, 10722, 8675, 8677, 4591, 14836, 503, 8701, 6657, 6659, 2575, 551, 4647, 553, 8751, 14895, 6711, 6713, 585, 587, 12877, 12879, 10833, 6739, 8789, 12886, 6743, 12888, 6744, 6745, 6747, 6741, 4701, 6742, 4703, 14944, 12897, 12899, 14948, 613, 12901, 12902, 12903, 10855, 12905, 12906, 12907, 10861, 8815, 10863, 6767, 6770, 4723, 6771, 6775, 4727, 642, 8843, 12940, 6801, 4754, 15007, 671, 6827, 12991, 8903, 15054, 4815, 15057, 15059, 6877, 10975, 6881, 6885, 6887, 2797, 2799, 13040, 753, 13046, 13047, 8951, 8953, 2816, 2817, 2819, 2821, 2822, 15111, 4872, 15113, 2826, 2825, 2827, 781, 775, 783, 2823, 8985, 8987, 6941, 6943, 15139, 15141, 15142, 15143, 15144, 15145, 15146, 15147, 13101, 13103, 9013, 2876, 6972, 4927, 15167, 13123, 15171, 15175, 13127, 15186, 6995, 9044, 6997, 2911, 15201, 868, 7021, 9071, 4977, 4979, 15227, 895, 13206, 2967, 7071, 13215, 5031, 5033, 15277, 15281, 15282, 15285, 15287, 11197, 11199, 9153, 5059, 5060, 7109, 5062, 5063, 5061, 5065, 5067, 3021, 3023, 11217, 11219, 11221, 11222, 11223, 9175, 11225, 11226, 11227, 9181, 7135, 9183, 5087, 5090, 3043, 5091, 5095, 5096, 3047, 15341, 15343, 7163, 5121, 11272, 13327, 11280, 5147, 15395, 11311, 7223, 15421, 3135, 13377, 13379, 5197, 9295, 5201, 5205, 5207, 1117, 1119, 11362, 1122, 3172, 1124, 7271, 11367, 7273, 15471, 1137, 1139, 1141, 13431, 1144, 13433, 1145, 1143, 1148, 1147, 7305, 7307, 5261, 5263, 13459, 15509, 13461, 13463, 13465, 13467, 13468, 11421, 1182, 11423, 3236, 7333, 13482, 3246, 15535, 3247, 13487, 11443, 13491, 13495, 11447, 5315, 5317, 5318, 15563, 11470, 1231, 13521, 5341, 7391, 3297, 3299, 13547, 1287, 15623, 13580, 5391, 11535, 3351, 3353, 13597, 13601, 13605, 13607, 9517, 9519, 7473, 3379, 5429, 3381, 15671, 3384, 15673, 3383, 3387, 3385, 1341, 9534, 1343, 9537, 9539, 9541, 9542, 9543, 9544, 9545, 7495, 9547, 9548, 7501, 5455, 7503, 3407, 1363, 3411, 3415, 1367, 15705, 15707, 13661, 13663, 5483, 9580, 3440, 3441, 15733, 9598, 11647, 3467, 13715, 13717, 9631, 5543, 13741, 1455, 15791, 11697, 11699, 3517, 7615, 3521, 3522, 3525, 3527, 5591, 9687, 5593, 13791, 13792, 1506, 3556, 11751, 11753, 5625, 5627, 3581, 3583, 15873, 11778, 11779, 13829, 11781, 11783, 11785, 11787, 9741, 9743, 9744, 5653, 15895, 1564, 15901, 13855, 1567, 15903, 11807, 9763, 11811, 11815, 9767, 3635, 11832, 13883, 11841, 3661, 1614, 5711, 1617, 1619, 3668, 11867, 7778, 13943, 3711, 9855, 1671, 1673, 11917, 16015, 11921, 11925, 11927, 7837, 7839, 5793, 1699, 3749, 1701, 13991, 1703, 13993, 1705, 1707, 1708, 7857, 7859, 7860, 7861, 7863, 5815, 7865, 7866, 14010, 7867, 5821, 3775, 5823, 1727, 1731, 1735, 1736, 14025, 14027, 11981, 11983, 14036, 3803, 1761, 14053, 9962, 9964, 3822, 9967, 1787, 12035, 7950, 7951, 14100, 3863, 12061, 14111, 10017, 10019, 1837, 5935, 1841, 1845, 1847, 3911, 8007, 3913, 12111, 10071, 10073, 3934, 3945, 3947, 16237, 1901, 1903, 16239, 14193, 1904, 10099, 12149, 16246, 10103, 10104, 10105, 10101, 10107, 8061, 8063, 16257, 16259, 16260, 16261, 3973, 16263, 14215, 16265, 16267, 14221, 12175, 14223, 10127, 8083, 10131, 10135, 8087, 1955, 1957, 12203, 10161, 16310, 16314, 1981, 4031, 16324, 10187, 10192, 16351, 12263, 2031, 8175, 2044, 10237, 14335}

Merge set for c5 and c15
Size: 135
Ids: {11778, 11779, 10245, 11781, 11783, 11785, 11787, 14, 19, 21, 23, 25, 27, 10270, 6177, 10274, 6179, 6183, 6185, 6187, 11832, 6739, 3668, 6741, 6742, 6743, 6744, 6745, 5205, 6747, 12897, 12899, 12903, 12905, 12907, 1137, 1139, 1143, 1145, 1147, 136, 13459, 13461, 11925, 13463, 13465, 13467, 13468, 1699, 165, 1701, 1703, 1705, 13482, 1707, 1708, 7857, 7859, 7863, 7865, 7867, 8419, 8421, 6885, 8423, 8424, 8425, 8427, 14577, 14579, 14583, 14585, 14587, 2817, 2819, 2823, 2825, 2827, 13580, 15139, 15141, 13605, 15143, 15144, 15145, 15146, 15147, 3379, 3381, 1845, 3383, 3384, 3385, 3387, 6972, 9537, 9539, 9543, 9545, 9547, 3440, 10099, 8565, 10101, 10103, 10104, 10105, 10107, 16257, 16259, 16263, 16265, 16267, 10127, 4497, 4499, 4503, 4505, 4507, 15282, 15285, 5059, 5060, 5061, 5062, 5063, 3525, 5065, 5067, 11217, 11219, 11223, 11225, 11227, 3556}

Merge set for c10 and c15
Size: 135
Ids: {11778, 11779, 10245, 11781, 11783, 11785, 11787, 14, 19, 21, 23, 25, 27, 10270, 6177, 10274, 6179, 6183, 6185, 6187, 11832, 6739, 3668, 6741, 6742, 6743, 6744, 6745, 5205, 6747, 12897, 12899, 12903, 12905, 12907, 1137, 1139, 1143, 1145, 1147, 136, 13459, 13461, 11925, 13463, 13465, 13467, 13468, 1699, 165, 1701, 1703, 1705, 13482, 1707, 1708, 7857, 7859, 7863, 7865, 7867, 8419, 8421, 6885, 8423, 8424, 8425, 8427, 14577, 14579, 14583, 14585, 14587, 2817, 2819, 2823, 2825, 2827, 13580, 15139, 15141, 13605, 15143, 15144, 15145, 15146, 15147, 3379, 3381, 1845, 3383, 3384, 3385, 3387, 6972, 9537, 9539, 9543, 9545, 9547, 3440, 10099, 8565, 10101, 10103, 10104, 10105, 10107, 16257, 16259, 16263, 16265, 16267, 10127, 4497, 4499, 4503, 4505, 4507, 15282, 15285, 5059, 5060, 5061, 5062, 5063, 3525, 5065, 5067, 11217, 11219, 11223, 11225, 11227, 3556}

Merge set for c5, c10 and c15
Size: 135
Ids: {11778, 11779, 10245, 11781, 11783, 11785, 11787, 14, 19, 21, 23, 25, 27, 10270, 6177, 10274, 6179, 6183, 6185, 6187, 11832, 6739, 3668, 6741, 6742, 6743, 6744, 6745, 5205, 6747, 12897, 12899, 12903, 12905, 12907, 1137, 1139, 1143, 1145, 1147, 136, 13459, 13461, 11925, 13463, 13465, 13467, 13468, 1699, 165, 1701, 1703, 1705, 13482, 1707, 1708, 7857, 7859, 7863, 7865, 7867, 8419, 8421, 6885, 8423, 8424, 8425, 8427, 14577, 14579, 14583, 14585, 14587, 2817, 2819, 2823, 2825, 2827, 13580, 15139, 15141, 13605, 15143, 15144, 15145, 15146, 15147, 3379, 3381, 1845, 3383, 3384, 3385, 3387, 6972, 9537, 9539, 9543, 9545, 9547, 3440, 10099, 8565, 10101, 10103, 10104, 10105, 10107, 16257, 16259, 16263, 16265, 16267, 10127, 4497, 4499, 4503, 4505, 4507, 15282, 15285, 5059, 5060, 5061, 5062, 5063, 3525, 5065, 5067, 11217, 11219, 11223, 11225, 11227, 3556}

In [63]:
c5_df[c5_df['experiment_id'].in(merge_ids)].sort_values(by=['coherence_med5', 'coherence_med10', 'coherence_med15'],
                                                 ascending=False)

SyntaxError: invalid syntax (<ipython-input-63-322e1ee9947b>, line 1)