In [3]:
import psycopg2
import pandas as pd
from django.conf import settings

In [4]:
connection = psycopg2.connect(user = settings.DATABASES["default"]["USER"],
                                  password = settings.DATABASES["default"]["PASSWORD"],
                                  host = settings.DATABASES["default"]["HOST"],
                                  port = settings.DATABASES["default"]["PORT"],
                                  database = settings.DATABASES["default"]["NAME"])
connection.autocommit=True
cursor = connection.cursor()

In [6]:
create_table_query = '''CREATE TABLE EDM2020_2020_02_19
    (EXPERIMENT_ID SERIAL PRIMARY KEY,
    DATASET TEXT NOT NULL,
    Q_MATRIX REAL ARRAY NOT NULL,
    X REAL ARRAY NULL,
    SP REAL ARRAY NOT NULL,
    X_TEST REAL ARRAY NULL,
    SP_TEST REAL ARRAY NOT NULL,
    SP_HAT REAL ARRAY NOT NULL,
    SK_HAT REAL ARRAY NOT NULL,
    Q_MATRIX_HAT REAL ARRAY NOT NULL,
    MU REAL NULL,
    CONCEPTS INTEGER NOT NULL,
    ATTEMPTS_TRAIN INTEGER NOT NULL,
    METHOD TEXT NOT NULL,
    Q_MATRIX_ERROR REAL NOT NULL,
    Q_MATRIX_RMSE REAL NOT NULL,
    RECONSTRUCTION_ERROR REAL NOT NULL,
    TRAIN_ERROR REAL NOT NULL,
    TEST_ERROR REAL NOT NULL,
    TRAIN_AUC REAL NULL,
    SECONDS INTEGER NOT NULL)
    '''

cursor.execute(create_table_query)
connection.commit()

In [5]:
create_table_query = '''CREATE TABLE EXPERIMENTS_2020_04_15
    (EXPERIMENT_ID SERIAL PRIMARY KEY,
    DATASET TEXT NOT NULL,
    X REAL ARRAY NOT NULL,
    Y REAL ARRAY NOT NULL,
    VECTORIZER TEXT NOT NULL,
    IS_BINARY BOOLEAN NOT NULL,
    MIN_DF REAL NOT NULL,
    NGRAMS INTEGER ARRAY NOT NULL,
    TOKEN INTEGER NOT NULL,
    DISTANCE TEXT NOT NULL,
    K INTEGER NOT NULL,
    METHOD TEXT NOT NULL,
    MODEL  bytea NOT NULL,
    CLUSTERING_TIME INTEGER NOT NULL,
    COHERENCE_SAMPLES5 REAL ARRAY NOT NULL,
    COHERENCE_SAMPLES10 REAL ARRAY NOT NULL,
    COHERENCE_SAMPLES15 REAL ARRAY NOT NULL,
    COHERENCE_MED5 REAL NOT NULL,
    COHERENCE_MED10 REAL NOT NULL,
    COHERENCE_MED15 REAL NOT NULL,
    COHERENCE_STD5 REAL NOT NULL,
    COHERENCE_STD10 REAL NOT NULL,
    COHERENCE_STD15 REAL NOT NULL,
    COHERENCE_TIME REAL NOT NULL,
    COHERENCE_K5 INTEGER NOT NULL,
    COHERENCE_K10 INTEGER NOT NULL,
    COHERENCE_K15 INTEGER NOT NULL)
    '''

cursor.execute(create_table_query)
connection.commit()

In [54]:
create_table_query = '''CREATE TABLE EXPERIMENTS_STABILITY_STATISTICS
    (STABILITY_ID SERIAL PRIMARY KEY,
    VECTORIZER TEXT NOT NULL,
    IS_BINARY BOOLEAN NOT NULL,
    MIN_DF REAL NOT NULL,
    DISTANCE TEXT NOT NULL,
    K INTEGER NOT NULL,
    METHOD TEXT NOT NULL,
    SAMPLES REAL ARRAY NOT NULL,
    MEAN REAL NOT NULL,
    STD REAL NOT NULL,
    MEDIAN REAL NOT NULL,
    IQR REAL NOT NULL
    )
    '''

cursor.execute(create_table_query)
connection.commit()

In [4]:
cols = ['dataset', 'k', 'min_df', 'is_binary', 'vectorizer', 'method', 'distance', 'clustering_time', 'coherence_time']
select_query = '''SELECT %s FROM EXPERIMENTS_STABILITY''' % ", ".join(cols)
cursor.execute(select_query)
r = cursor.fetchall()
# print(r)

In [5]:
df = pd.DataFrame(r, columns=cols)

In [6]:
df['total_time'] = df.sum(axis=1)

In [7]:
df[(df['dataset'].str.contains('dataset'))].sort_values(['k','min_df', 'is_binary','vectorizer'])
#    & (df['vectorizer'] == 'TfidfVectorizer') & (df['is_binary'] == True) & (df['distance'] == 'euclidean')
# df

,dataset,k,min_df,is_binary,vectorizer,method,distance,clustering_time,coherence_time,total_time
29,dataset0,2,0.05,False,CountVectorizer,nmf,euclidean,0,0.023457,2.073457
30,dataset0,2,0.05,False,CountVectorizer,lda,euclidean,0,0.012981,2.062981
1587,dataset1,2,0.05,False,CountVectorizer,nmf,euclidean,0,0.033381,2.083381
1599,dataset1,2,0.05,False,CountVectorizer,lda,euclidean,0,0.013175,2.063175
3270,dataset2,2,0.05,False,CountVectorizer,nmf,euclidean,0,0.033350,2.083350
3282,dataset2,2,0.05,False,CountVectorizer,lda,euclidean,0,0.011714,2.061714
5125,dataset3,2,0.05,False,CountVectorizer,nmf,euclidean,0,0.032648,2.082648
5126,dataset3,2,0.05,False,CountVectorizer,lda,euclidean,0,0.013141,2.063141
6648,dataset4,2,0.05,False,CountVectorizer,nmf,euclidean,0,0.031143,2.081143
6812,dataset4,2,0.05,False,CountVectorizer,lda,euclidean,0,0.013102,2.063102
8331,dataset5,2,0.05,False,CountVectorizer,lda,euclidean,0,0.013055,2.063055
8498,dataset5,2,0.05,False,CountVectorizer,nmf,euclidean,0,0.029349,2.079349
10002,dataset6,2,0.05,False,CountVectorizer,lda,euclidean,0,0.013032,2.063032
10167,dataset6,2,0.05,False,CountVectorizer,nmf,euclidean,0,0.033932,2.083932
11835,dataset7,2,0.05,False,CountVectorizer,nmf,euclidean,0,0.029233,2.079233
11836,dataset7,2,0.05,False,CountVectorizer,lda,euclidean,0,0.011938,2.061938
13461,dataset8,2,0.05,False,CountVectorizer,lda,euclidean,0,0.013103,2.063103
13493,dataset8,2,0.05,False,CountVectorizer,nmf,euclidean,0,0.034000,2.084000
15000,dataset9,2,0.05,False,CountVectorizer,lda,euclidean,0,0.011736,2.061736
15167,dataset9,2,0.05,False,CountVectorizer,nmf,euclidean,0,0.029517,2.079517
1177,dataset0,2,0.05,False,NCutVectorizer,nmf,euclidean,0,0.008647,2.058647
1178,dataset0,2,0.05,False,NCutVectorizer,lda,euclidean,0,0.009108,2.059108
2873,dataset1,2,0.05,False,NCutVectorizer,nmf,euclidean,0,0.012464,2.062464
2874,dataset1,2,0.05,False,NCutVectorizer,lda,euclidean,0,0.004786,2.054786
4562,dataset2,2,0.05,False,NCutVectorizer,nmf,euclidean,0,0.009196,2.059196
4563,dataset2,2,0.05,False,NCutVectorizer,lda,euclidean,0,0.003928,2.053928
6243,dataset3,2,0.05,False,NCutVectorizer,nmf,euclidean,0,0.009892,2.059892
6244,dataset3,2,0.05,False,NCutVectorizer,lda,euclidean,0,0.009077,2.059077
7926,dataset4,2,0.05,False,NCutVectorizer,nmf,euclidean,0,0.009727,2.059727
7927,dataset4,2,0.05,False,NCutVectorizer,lda,euclidean,0,0.009012,2.059012
...,...,...,...,...,...,...,...,...,...,...
10117,dataset5,15,0.50,True,NCutVectorizer,nmf,euclidean,0,0.013473,16.513473
10118,dataset5,15,0.50,True,NCutVectorizer,lda,euclidean,0,0.002735,16.502735
11784,dataset6,15,0.50,True,NCutVectorizer,nmf,euclidean,0,0.014070,16.514070
11785,dataset6,15,0.50,True,NCutVectorizer,lda,euclidean,0,0.002742,16.502742
13443,dataset7,15,0.50,True,NCutVectorizer,nmf,euclidean,0,0.006372,16.506372
13444,dataset7,15,0.50,True,NCutVectorizer,lda,euclidean,0,0.001750,16.501750
15114,dataset8,15,0.50,True,NCutVectorizer,nmf,euclidean,0,0.008782,16.508782
15115,dataset8,15,0.50,True,NCutVectorizer,lda,euclidean,0,0.002758,16.502758
16770,dataset9,15,0.50,True,NCutVectorizer,nmf,euclidean,0,0.009452,16.509452
16771,dataset9,15,0.50,True,NCutVectorizer,lda,euclidean,0,0.002775,16.502775
1132,dataset0,15,0.50,True,TfidfVectorizer,nmf,euclidean,0,0.012545,16.512545
1133,dataset0,15,0.50,True,TfidfVectorizer,lda,euclidean,0,0.003708,16.503708
2828,dataset1,15,0.50,True,TfidfVectorizer,nmf,euclidean,0,0.024556,16.524556
2829,dataset1,15,0.50,True,TfidfVectorizer,lda,euclidean,0,0.002887,16.502887
4517,dataset2,15,0.50,True,TfidfVectorizer,nmf,euclidean,0,0.012277,16.512277
4518,dataset2,15,0.50,True,TfidfVectorizer,lda,euclidean,0,0.002820,16.502820
6194,dataset3,15,0.50,True,TfidfVectorizer,nmf,euclidean,0,0.012474,16.512474
6195,dataset3,15,0.50,True,TfidfVectorizer,lda,euclidean,0,0.002730,16.502730
7879,dataset4,15,0.50,True,TfidfVectorizer,nmf,euclidean,0,0.012067,16.512067
7880,dataset4,15,0.50,True,TfidfVectorizer,lda,euclidean,0,0.003781,16.503781
9560,dataset5,15,0.50,True,TfidfVectorizer,nmf,euclidean,0,0.012681,16.512681
9563,dataset5,15,0.50,True,TfidfVectorizer,lda,euclidean,0,0.003445,16.503445
11225,dataset6,15,0.50,True,TfidfVectorizer,nmf,euclidean,0,0.012134,16.512134
11226,dataset6,15,0.50,True,TfidfVectorizer,lda,euclidean,0,0.002755,16.502755
12904,dataset7,15,0.50,True,TfidfVectorizer,nmf,euclidean,0,0.013256,16.513256
12905,dataset7,15,0.50,True,TfidfVectorizer,lda,euclidean,0,0.002827,16.502827
14558,dataset8,15,0.50,True,TfidfVectorizer,nmf,euclidean,0,0.022831,16.522831
14559,dataset8,15,0.50,True,TfidfVectorizer,lda,euclidean,0,0.002709,16.502709
16227,dataset9,15,0.50,True,TfidfVectorizer,nmf,euclidean,0,0.015770,16.515770
16228,dataset9,15,0.50,True,TfidfVectorizer,lda,euclidean,0,0.003751,16.503751

In [293]:
# c5_df[['min_df', 'is_binary', 'vectorizer', 'method', 'distance', 'k']].drop_duplicates()

      min_df  is_binary       vectorizer method   distance   k
0       0.05       True  TfidfVectorizer    lda  euclidean  13
1       0.05       True  TfidfVectorizer    lda  euclidean  11
2       0.35       True   NCutVectorizer    nmf  euclidean   7
3       0.40       True  CountVectorizer    nmf  euclidean  13
4       0.50      False   NCutVectorizer    nmf  euclidean  12
5       0.45      False   NCutVectorizer    nmf  euclidean  15
6       0.50      False  CountVectorizer    nmf  euclidean  11
7       0.05       True  CountVectorizer    nmf  euclidean  15
8       0.20      False  CountVectorizer    nmf  euclidean  15
9       0.05       True  CountVectorizer    lda  euclidean  13
10      0.30       True  CountVectorizer    nmf  euclidean  12
11      0.25      False  CountVectorizer    nmf  euclidean  13
12      0.35      False   NCutVectorizer    lda  euclidean   9
13      0.50      False   NCutVectorizer    nmf  euclidean  13
14      0.50      False   NCutVectorizer    nmf  euclidean  15
15      0.50      False   NCutVectorizer    nmf  euclidean  14
16      0.30      False  TfidfVectorizer    nmf  euclidean  15
17      0.45      False   NCutVectorizer    nmf  euclidean  14
18      0.05       True   NCutVectorizer    lda  euclidean  14
19      0.20      False  TfidfVectorizer    nmf  euclidean  15
20      0.40      False  CountVectorizer    nmf  euclidean  13
21      0.15      False  CountVectorizer    nmf  euclidean  10
22      0.35      False  CountVectorizer    nmf  euclidean  14
23      0.50      False  TfidfVectorizer    nmf  euclidean  14
24      0.50      False  TfidfVectorizer    nmf  euclidean  15
25      0.35       True  CountVectorizer    nmf  euclidean   9
26      0.40       True   NCutVectorizer    nmf  euclidean   8
27      0.20       True  TfidfVectorizer    nmf  euclidean  14
28      0.45      False  CountVectorizer    nmf  euclidean  15
29      0.50      False  CountVectorizer    nmf  euclidean  12
...      ...        ...              ...    ...        ...  ..
1661    0.15      False   NCutVectorizer    lda  euclidean  13
1662    0.20       True   NCutVectorizer    lda  euclidean  14
1663    0.30       True  TfidfVectorizer    nmf  euclidean   2
1664    0.20       True  TfidfVectorizer    nmf  euclidean   2
1665    0.10       True   NCutVectorizer    lda  euclidean   2
1666    0.10      False  TfidfVectorizer    lda  euclidean   4
1667    0.05      False   NCutVectorizer    nmf  euclidean   4
1668    0.10      False   NCutVectorizer    lda  euclidean   5
1669    0.10      False   NCutVectorizer    nmf  euclidean   4
1670    0.15      False  TfidfVectorizer    lda  euclidean   3
1671    0.05      False   NCutVectorizer    lda  euclidean   9
1672    0.15       True  TfidfVectorizer    nmf  euclidean   2
1673    0.20       True  TfidfVectorizer    lda  euclidean   2
1674    0.15       True  TfidfVectorizer    lda  euclidean  14
1675    0.25       True  TfidfVectorizer    nmf  euclidean   2
1676    0.10      False   NCutVectorizer    nmf  euclidean   3
1677    0.20      False  TfidfVectorizer    lda  euclidean   4
1678    0.10       True   NCutVectorizer    lda  euclidean  13
1679    0.15       True  TfidfVectorizer    lda  euclidean  11
1680    0.10      False   NCutVectorizer    nmf  euclidean   2
1681    0.05      False  TfidfVectorizer    lda  euclidean   5
1682    0.05      False  TfidfVectorizer    lda  euclidean   8
1683    0.05      False   NCutVectorizer    lda  euclidean   6
1684    0.10      False  TfidfVectorizer    lda  euclidean   2
1685    0.05      False  TfidfVectorizer    lda  euclidean   2
1686    0.05      False   NCutVectorizer    lda  euclidean   7
1687    0.05      False  TfidfVectorizer    lda  euclidean   6
1688    0.05      False  TfidfVectorizer    lda  euclidean  15
1689    0.05      False  TfidfVectorizer    lda  euclidean  13
1690    0.20      False  TfidfVectorizer    lda  euclidean  13

[1624 rows x 6 columns]

In [3]:
drop_query = '''DROP TABLE EXPERIMENTS_2020_01_27'''
cursor.execute(drop_query)
connection.commit()

In [295]:
create_results_table = '''CREATE TABLE EXPERIMENTS_SOLUTION_RESULT
    (EXPERIMENT_ID INTEGER REFERENCES EXPERIMENTS(EXPERIMENT_ID),
    GAP_K INTEGER NOT NULL,
    GAP_K2 INTEGER NOT NULL,
    SILHOUETTE_K INTEGER NOT NULL,
    SILHOUETTE_K2 INTEGER NOT NULL,
    COHERENCE_K5 INTEGER NOT NULL,
    COHERENCE_K2_5 INTEGER NOT NULL,
    COHERENCE_K10 INTEGER NOT NULL,
    COHERENCE_K2_10 INTEGER NOT NULL,
    COHERENCE_K15 INTEGER NOT NULL,
    COHERENCE_K2_15 INTEGER NOT NULL)
    '''

cursor.execute(create_results_table)
connection.commit()

In [296]:
alter_results_table = """ALTER TABLE EXPERIMENTS_SOLUTION_RESULT
 ADD CONSTRAINT UC_SOLUTION_RESULT UNIQUE (EXPERIMENT_ID)"""

cursor.execute(alter_results_table)
connection.commit()

In [30]:
# cols_result = ["gap_k", "gap_k2", "silhouette_k", "silhouette_k2", "coherence_k", "coherence_k2"]
# cols_result_sql = ["experiments_result.%s" % item for item in cols_result]
cols_experiment = ['experiment_id', 'k', 'dataset', 'min_df', 'is_binary', 'vectorizer', 'method', 'distance', 'coherence_med5', 'coherence_med10','coherence_med15']
cols_experiment_sql = ["EXPERIMENTS_STABILITY.%s" % item for item in cols_experiment]

select_query = '''SELECT %s FROM EXPERIMENTS_STABILITY where dataset like 'dataset%%' order by coherence_med5 desc, coherence_med15 desc, coherence_med10 desc  '''  % ", ".join(cols_experiment_sql)
# select_query = '''SELECT %s FROM EXPERIMENTS_STABILITY where dataset like 'dataset%%' order by coherence_med10 desc, coherence_med5 desc, coherence_med15 desc  '''  % ", ".join(cols_experiment_sql)
# select_query = '''SELECT %s FROM EXPERIMENTS_STABILITY where dataset like 'dataset%%' order by coherence_med15 desc, coherence_med5 desc, coherence_med10 desc  '''  % ", ".join(cols_experiment_sql)
cursor.execute(select_query)
r = cursor.fetchall()

In [31]:
c5_df = pd.DataFrame(r, columns=cols_experiment).dropna()

In [32]:
c5_df

,experiment_id,k,dataset,min_df,is_binary,vectorizer,method,distance,coherence_med5,coherence_med10,coherence_med15
11,6178,10,dataset3,0.05,True,NCutVectorizer,lda,euclidean,0.009950,-0.130145,-0.235746
12,7950,14,dataset4,0.10,False,NCutVectorizer,lda,euclidean,0.009950,-0.254308,-0.672025
13,14572,7,dataset8,0.05,True,NCutVectorizer,lda,euclidean,0.009950,-0.122830,-1.308660
14,6212,13,dataset3,0.05,False,NCutVectorizer,lda,euclidean,0.007469,0.007469,-0.331439
15,11362,12,dataset6,0.15,False,NCutVectorizer,lda,euclidean,0.006639,-0.047629,-0.663792
16,9534,8,dataset5,0.05,True,NCutVectorizer,lda,euclidean,0.006639,-0.307062,-1.048600
17,7778,12,dataset4,0.45,False,TfidfVectorizer,lda,euclidean,0.005974,-0.364337,-1.638310
18,8288,15,dataset4,0.40,False,NCutVectorizer,lda,euclidean,0.005808,-0.046629,-0.182594
19,16324,15,dataset9,0.10,True,NCutVectorizer,lda,euclidean,0.005689,-0.093200,-0.480662
20,6238,12,dataset3,0.10,True,NCutVectorizer,lda,euclidean,0.005689,-0.093200,-0.645488
21,9744,15,dataset5,0.20,False,NCutVectorizer,lda,euclidean,0.005360,-0.090076,-0.262668
22,10495,13,dataset6,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.148251,-0.381515
23,13855,13,dataset8,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.186211,-0.423334
24,8815,13,dataset5,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.166291,-0.443332
25,2095,13,dataset1,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.186211,-0.443332
26,12175,13,dataset7,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.230499,-0.443332
27,3775,13,dataset2,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.240773,-0.443332
28,5455,13,dataset3,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.240773,-0.443332
29,415,13,dataset0,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.240773,-0.443332
30,7135,13,dataset4,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.240773,-0.443332
31,15535,13,dataset9,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.240773,-0.443332
32,9962,12,dataset5,0.40,False,NCutVectorizer,lda,euclidean,0.005202,-0.194146,-0.945303
33,16732,9,dataset9,0.45,False,NCutVectorizer,lda,euclidean,0.005202,-0.177314,-0.997257
34,4872,15,dataset2,0.35,False,NCutVectorizer,lda,euclidean,0.005183,-0.068694,-0.988133
35,1506,12,dataset0,0.35,False,NCutVectorizer,lda,euclidean,0.005142,-0.090099,-0.962803
36,3172,5,dataset1,0.35,False,NCutVectorizer,lda,euclidean,0.005136,-0.075735,-0.996573
37,14640,13,dataset8,0.10,True,NCutVectorizer,lda,euclidean,0.005114,-0.225640,-0.497771
38,2816,9,dataset1,0.05,True,NCutVectorizer,lda,euclidean,0.005070,-0.312131,-0.273566
39,9548,15,dataset5,0.05,True,NCutVectorizer,lda,euclidean,0.005070,-0.056813,-0.439511
40,868,15,dataset0,0.30,True,TfidfVectorizer,lda,euclidean,0.005070,-0.054456,-0.449350
...,...,...,...,...,...,...,...,...,...,...,...
16770,10682,8,dataset6,0.05,False,TfidfVectorizer,lda,euclidean,-1.143830,-0.502841,-0.751778
16771,10694,14,dataset6,0.05,False,TfidfVectorizer,lda,euclidean,-1.143830,-0.749171,-0.889086
16772,16282,8,dataset9,0.05,False,NCutVectorizer,lda,euclidean,-1.179370,-0.647454,-0.511546
16773,2836,5,dataset1,0.05,False,NCutVectorizer,lda,euclidean,-1.243320,-2.145270,-1.867990
16774,9116,9,dataset5,0.15,False,TfidfVectorizer,lda,euclidean,-1.318020,-0.527539,-0.666581
16775,592,3,dataset0,0.05,False,TfidfVectorizer,lda,euclidean,-1.320840,-0.584269,-0.399673
16776,15722,8,dataset9,0.05,False,TfidfVectorizer,lda,euclidean,-1.320840,-0.584269,-0.656058
16777,12892,7,dataset7,0.05,True,NCutVectorizer,lda,euclidean,-1.323240,-0.651835,-0.498591
16778,7328,11,dataset4,0.05,False,TfidfVectorizer,lda,euclidean,-1.337630,-0.832142,-0.805054
16779,11246,10,dataset6,0.05,False,NCutVectorizer,lda,euclidean,-1.370810,-0.766404,-0.810372
16780,15736,15,dataset9,0.05,False,TfidfVectorizer,lda,euclidean,-1.494190,-2.018700,-1.732420
16781,8994,4,dataset5,0.05,False,TfidfVectorizer,lda,euclidean,-1.520390,-1.181200,-1.245380
16782,12350,2,dataset7,0.05,False,TfidfVectorizer,lda,euclidean,-1.528840,-1.437200,-1.259460
16783,14042,8,dataset8,0.05,False,TfidfVectorizer,lda,euclidean,-1.557880,-1.356540,-1.566580
16784,9002,8,dataset5,0.05,False,TfidfVectorizer,lda,euclidean,-1.597290,-0.773403,-0.979004
16785,9016,15,dataset5,0.05,False,TfidfVectorizer,lda,euclidean,-1.649270,-2.320230,-2.241920
16786,672,15,dataset0,0.10,False,TfidfVectorizer,lda,euclidean,-1.701720,-0.863143,-1.310660
16787,760,3,dataset0,0.20,False,TfidfVectorizer,lda,euclidean,-1.753730,-1.250600,-1.140230
16788,4510,2,dataset2,0.05,False,NCutVectorizer,lda,euclidean,-1.756260,-1.163410,-1.005020
16789,11218,10,dataset6,0.05,True,NCutVectorizer,lda,euclidean,-1.830580,-1.549420,-1.841350
16790,15682,2,dataset9,0.05,True,TfidfVectorizer,lda,euclidean,-1.882450,-1.802880,-1.917300
16791,3954,4,dataset2,0.05,False,TfidfVectorizer,lda,euclidean,-1.974730,-1.090740,-0.818166
16792,11208,5,dataset6,0.05,True,NCutVectorizer,lda,euclidean,-1.986150,-1.830350,-1.256210
16793,14600,7,dataset8,0.05,False,NCutVectorizer,lda,euclidean,-2.017500,-1.320570,-0.941224
16794,15764,15,dataset9,0.10,True,TfidfVectorizer,lda,euclidean,-2.041700,-0.677100,-0.999055
16795,2286,10,dataset1,0.05,False,TfidfVectorizer,lda,euclidean,-2.066620,-1.618520,-2.231890
16796,11266,6,dataset6,0.10,True,NCutVectorizer,lda,euclidean,-2.246390,-1.050740,-1.195110
16797,9524,3,dataset5,0.05,True,NCutVectorizer,lda,euclidean,-2.649060,-2.124970,-2.397270
16798,5638,6,dataset3,0.05,False,TfidfVectorizer,lda,euclidean,-2.850230,-1.924210,-1.642100
16799,14040,7,dataset8,0.05,False,TfidfVectorizer,lda,euclidean,-3.449040,-2.868100,-2.462440

In [29]:
c10_df

,experiment_id,k,dataset,min_df,is_binary,vectorizer,method,distance,coherence_med5,coherence_med10,coherence_med15
11,6178,10,dataset3,0.05,True,NCutVectorizer,lda,euclidean,0.009950,-0.130145,-0.235746
12,7950,14,dataset4,0.10,False,NCutVectorizer,lda,euclidean,0.009950,-0.254308,-0.672025
13,14572,7,dataset8,0.05,True,NCutVectorizer,lda,euclidean,0.009950,-0.122830,-1.308660
14,6212,13,dataset3,0.05,False,NCutVectorizer,lda,euclidean,0.007469,0.007469,-0.331439
15,11362,12,dataset6,0.15,False,NCutVectorizer,lda,euclidean,0.006639,-0.047629,-0.663792
16,9534,8,dataset5,0.05,True,NCutVectorizer,lda,euclidean,0.006639,-0.307062,-1.048600
17,7778,12,dataset4,0.45,False,TfidfVectorizer,lda,euclidean,0.005974,-0.364337,-1.638310
18,8288,15,dataset4,0.40,False,NCutVectorizer,lda,euclidean,0.005808,-0.046629,-0.182594
19,16324,15,dataset9,0.10,True,NCutVectorizer,lda,euclidean,0.005689,-0.093200,-0.480662
20,6238,12,dataset3,0.10,True,NCutVectorizer,lda,euclidean,0.005689,-0.093200,-0.645488
21,9744,15,dataset5,0.20,False,NCutVectorizer,lda,euclidean,0.005360,-0.090076,-0.262668
22,10495,13,dataset6,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.148251,-0.381515
23,13855,13,dataset8,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.186211,-0.423334
24,8815,13,dataset5,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.166291,-0.443332
25,2095,13,dataset1,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.186211,-0.443332
26,12175,13,dataset7,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.230499,-0.443332
27,3775,13,dataset2,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.240773,-0.443332
28,5455,13,dataset3,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.240773,-0.443332
29,415,13,dataset0,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.240773,-0.443332
30,7135,13,dataset4,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.240773,-0.443332
31,15535,13,dataset9,0.40,True,CountVectorizer,nmf,euclidean,0.005269,-0.240773,-0.443332
32,9962,12,dataset5,0.40,False,NCutVectorizer,lda,euclidean,0.005202,-0.194146,-0.945303
33,16732,9,dataset9,0.45,False,NCutVectorizer,lda,euclidean,0.005202,-0.177314,-0.997257
34,4872,15,dataset2,0.35,False,NCutVectorizer,lda,euclidean,0.005183,-0.068694,-0.988133
35,1506,12,dataset0,0.35,False,NCutVectorizer,lda,euclidean,0.005142,-0.090099,-0.962803
36,3172,5,dataset1,0.35,False,NCutVectorizer,lda,euclidean,0.005136,-0.075735,-0.996573
37,14640,13,dataset8,0.10,True,NCutVectorizer,lda,euclidean,0.005114,-0.225640,-0.497771
38,2816,9,dataset1,0.05,True,NCutVectorizer,lda,euclidean,0.005070,-0.312131,-0.273566
39,9548,15,dataset5,0.05,True,NCutVectorizer,lda,euclidean,0.005070,-0.056813,-0.439511
40,868,15,dataset0,0.30,True,TfidfVectorizer,lda,euclidean,0.005070,-0.054456,-0.449350
...,...,...,...,...,...,...,...,...,...,...,...
16770,10682,8,dataset6,0.05,False,TfidfVectorizer,lda,euclidean,-1.143830,-0.502841,-0.751778
16771,10694,14,dataset6,0.05,False,TfidfVectorizer,lda,euclidean,-1.143830,-0.749171,-0.889086
16772,16282,8,dataset9,0.05,False,NCutVectorizer,lda,euclidean,-1.179370,-0.647454,-0.511546
16773,2836,5,dataset1,0.05,False,NCutVectorizer,lda,euclidean,-1.243320,-2.145270,-1.867990
16774,9116,9,dataset5,0.15,False,TfidfVectorizer,lda,euclidean,-1.318020,-0.527539,-0.666581
16775,592,3,dataset0,0.05,False,TfidfVectorizer,lda,euclidean,-1.320840,-0.584269,-0.399673
16776,15722,8,dataset9,0.05,False,TfidfVectorizer,lda,euclidean,-1.320840,-0.584269,-0.656058
16777,12892,7,dataset7,0.05,True,NCutVectorizer,lda,euclidean,-1.323240,-0.651835,-0.498591
16778,7328,11,dataset4,0.05,False,TfidfVectorizer,lda,euclidean,-1.337630,-0.832142,-0.805054
16779,11246,10,dataset6,0.05,False,NCutVectorizer,lda,euclidean,-1.370810,-0.766404,-0.810372
16780,15736,15,dataset9,0.05,False,TfidfVectorizer,lda,euclidean,-1.494190,-2.018700,-1.732420
16781,8994,4,dataset5,0.05,False,TfidfVectorizer,lda,euclidean,-1.520390,-1.181200,-1.245380
16782,12350,2,dataset7,0.05,False,TfidfVectorizer,lda,euclidean,-1.528840,-1.437200,-1.259460
16783,14042,8,dataset8,0.05,False,TfidfVectorizer,lda,euclidean,-1.557880,-1.356540,-1.566580
16784,9002,8,dataset5,0.05,False,TfidfVectorizer,lda,euclidean,-1.597290,-0.773403,-0.979004
16785,9016,15,dataset5,0.05,False,TfidfVectorizer,lda,euclidean,-1.649270,-2.320230,-2.241920
16786,672,15,dataset0,0.10,False,TfidfVectorizer,lda,euclidean,-1.701720,-0.863143,-1.310660
16787,760,3,dataset0,0.20,False,TfidfVectorizer,lda,euclidean,-1.753730,-1.250600,-1.140230
16788,4510,2,dataset2,0.05,False,NCutVectorizer,lda,euclidean,-1.756260,-1.163410,-1.005020
16789,11218,10,dataset6,0.05,True,NCutVectorizer,lda,euclidean,-1.830580,-1.549420,-1.841350
16790,15682,2,dataset9,0.05,True,TfidfVectorizer,lda,euclidean,-1.882450,-1.802880,-1.917300
16791,3954,4,dataset2,0.05,False,TfidfVectorizer,lda,euclidean,-1.974730,-1.090740,-0.818166
16792,11208,5,dataset6,0.05,True,NCutVectorizer,lda,euclidean,-1.986150,-1.830350,-1.256210
16793,14600,7,dataset8,0.05,False,NCutVectorizer,lda,euclidean,-2.017500,-1.320570,-0.941224
16794,15764,15,dataset9,0.10,True,TfidfVectorizer,lda,euclidean,-2.041700,-0.677100,-0.999055
16795,2286,10,dataset1,0.05,False,TfidfVectorizer,lda,euclidean,-2.066620,-1.618520,-2.231890
16796,11266,6,dataset6,0.10,True,NCutVectorizer,lda,euclidean,-2.246390,-1.050740,-1.195110
16797,9524,3,dataset5,0.05,True,NCutVectorizer,lda,euclidean,-2.649060,-2.124970,-2.397270
16798,5638,6,dataset3,0.05,False,TfidfVectorizer,lda,euclidean,-2.850230,-1.924210,-1.642100
16799,14040,7,dataset8,0.05,False,TfidfVectorizer,lda,euclidean,-3.449040,-2.868100,-2.462440

In [21]:
c15_df

,experiment_id,k,dataset,min_df,is_binary,vectorizer,method,distance,coherence_med5,coherence_med10,coherence_med15
0,15144,13,dataset9,0.05,True,CountVectorizer,lda,euclidean,0.004988,0.004988,0.004988
1,8424,13,dataset5,0.05,True,CountVectorizer,lda,euclidean,0.003328,0.003328,0.003328
2,11778,10,dataset7,0.05,True,CountVectorizer,lda,euclidean,0.002912,0.002912,0.002912
3,3440,13,dataset2,0.10,True,CountVectorizer,lda,euclidean,0.002497,0.002497,0.002497
4,14,8,dataset0,0.05,True,CountVectorizer,lda,euclidean,0.003328,0.003328,0.001665
5,10102,12,dataset6,0.05,True,CountVectorizer,lda,euclidean,0.001665,0.001665,-0.010445
6,8418,10,dataset5,0.05,True,CountVectorizer,lda,euclidean,0.002081,0.001332,-0.013532
7,12058,10,dataset7,0.30,True,CountVectorizer,lda,euclidean,0.001832,0.001457,-0.014226
8,6744,13,dataset4,0.05,True,CountVectorizer,lda,euclidean,0.002497,0.002497,-0.015455
9,6747,15,dataset4,0.05,True,CountVectorizer,nmf,euclidean,0.003328,0.003328,-0.016571
10,1707,15,dataset1,0.05,True,CountVectorizer,nmf,euclidean,0.003328,0.003328,-0.016571
11,3387,15,dataset2,0.05,True,CountVectorizer,nmf,euclidean,0.003328,0.003328,-0.016571
12,15147,15,dataset9,0.05,True,CountVectorizer,nmf,euclidean,0.003328,0.003328,-0.016571
13,5067,15,dataset3,0.05,True,CountVectorizer,nmf,euclidean,0.003328,0.003328,-0.016571
14,27,15,dataset0,0.05,True,CountVectorizer,nmf,euclidean,0.003328,0.003328,-0.016571
15,10107,15,dataset6,0.05,True,CountVectorizer,nmf,euclidean,0.003328,0.003328,-0.016571
16,13467,15,dataset8,0.05,True,CountVectorizer,nmf,euclidean,0.003328,0.003328,-0.016571
17,11787,15,dataset7,0.05,True,CountVectorizer,nmf,euclidean,0.003328,0.003328,-0.016571
18,8427,15,dataset5,0.05,True,CountVectorizer,nmf,euclidean,0.003328,0.003328,-0.016571
19,13463,13,dataset8,0.05,True,CountVectorizer,nmf,euclidean,0.002497,0.002497,-0.016571
20,3383,13,dataset2,0.05,True,CountVectorizer,nmf,euclidean,0.002497,0.002497,-0.016571
21,1703,13,dataset1,0.05,True,CountVectorizer,nmf,euclidean,0.002497,0.002497,-0.016571
22,6743,13,dataset4,0.05,True,CountVectorizer,nmf,euclidean,0.002497,0.002497,-0.016571
23,5063,13,dataset3,0.05,True,CountVectorizer,nmf,euclidean,0.002497,0.002497,-0.016571
24,15143,13,dataset9,0.05,True,CountVectorizer,nmf,euclidean,0.002497,0.002497,-0.016571
25,23,13,dataset0,0.05,True,CountVectorizer,nmf,euclidean,0.002497,0.002497,-0.016571
26,11783,13,dataset7,0.05,True,CountVectorizer,nmf,euclidean,0.002497,0.002497,-0.016571
27,10103,13,dataset6,0.05,True,CountVectorizer,nmf,euclidean,0.002497,0.002497,-0.016571
28,8423,13,dataset5,0.05,True,CountVectorizer,nmf,euclidean,0.002497,0.002497,-0.016571
29,5062,12,dataset3,0.05,True,CountVectorizer,lda,euclidean,0.002497,0.001998,-0.016571
...,...,...,...,...,...,...,...,...,...,...,...
16770,11166,12,dataset6,0.50,True,TfidfVectorizer,lda,euclidean,-0.039145,-0.216393,-2.146320
16771,1074,6,dataset0,0.50,True,TfidfVectorizer,lda,euclidean,-0.039145,-0.216393,-2.146320
16772,4436,7,dataset2,0.50,True,TfidfVectorizer,lda,euclidean,-0.039145,-0.216393,-2.146320
16773,6124,11,dataset3,0.50,True,TfidfVectorizer,lda,euclidean,-0.039145,-0.216393,-2.146320
16774,14530,14,dataset8,0.50,True,TfidfVectorizer,lda,euclidean,-0.039145,-0.216393,-2.146320
16775,2758,8,dataset1,0.50,True,TfidfVectorizer,lda,euclidean,-0.039145,-0.216393,-2.146320
16776,7796,7,dataset4,0.50,True,TfidfVectorizer,lda,euclidean,-0.039145,-0.216393,-2.146320
16777,1082,10,dataset0,0.50,True,TfidfVectorizer,lda,euclidean,-0.039145,-0.216393,-2.146320
16778,12836,7,dataset7,0.50,True,TfidfVectorizer,lda,euclidean,-0.039145,-0.216393,-2.146320
16779,12844,11,dataset7,0.50,True,TfidfVectorizer,lda,euclidean,-0.039145,-0.216393,-2.146320
16780,2756,7,dataset1,0.50,True,TfidfVectorizer,lda,euclidean,-0.039145,-0.216393,-2.146320
16781,14522,10,dataset8,0.50,True,TfidfVectorizer,lda,euclidean,-0.039145,-0.216393,-2.146320
16782,9486,12,dataset5,0.50,True,TfidfVectorizer,lda,euclidean,-0.039145,-0.216393,-2.146320
16783,7836,13,dataset4,0.50,False,TfidfVectorizer,lda,euclidean,-0.054707,-0.132769,-2.146320
16784,6156,13,dataset3,0.50,False,TfidfVectorizer,lda,euclidean,-0.054707,-0.138792,-2.146320
16785,4446,12,dataset2,0.50,True,TfidfVectorizer,lda,euclidean,-0.035869,-0.247793,-2.155500
16786,8976,9,dataset5,0.05,True,TfidfVectorizer,lda,euclidean,-0.676735,-1.586750,-2.166700
16787,11190,10,dataset6,0.50,False,TfidfVectorizer,lda,euclidean,-0.016810,-0.574201,-2.221960
16788,2286,10,dataset1,0.05,False,TfidfVectorizer,lda,euclidean,-2.066620,-1.618520,-2.231890
16789,9016,15,dataset5,0.05,False,TfidfVectorizer,lda,euclidean,-1.649270,-2.320230,-2.241920
16790,556,13,dataset0,0.50,False,CountVectorizer,lda,euclidean,0.001249,-0.584269,-2.267860
16791,9518,14,dataset5,0.50,False,TfidfVectorizer,lda,euclidean,-0.037975,-0.643190,-2.278230
16792,4422,14,dataset2,0.45,False,TfidfVectorizer,lda,euclidean,0.002497,-1.015630,-2.297610
16793,4478,14,dataset2,0.50,False,TfidfVectorizer,lda,euclidean,-0.037087,-1.015630,-2.297610
16794,15070,4,dataset8,0.50,True,NCutVectorizer,lda,euclidean,0.001665,-0.277620,-2.332520
16795,9524,3,dataset5,0.05,True,NCutVectorizer,lda,euclidean,-2.649060,-2.124970,-2.397270
16796,14552,11,dataset8,0.50,False,TfidfVectorizer,lda,euclidean,-0.038907,-0.665508,-2.448800
16797,14040,7,dataset8,0.05,False,TfidfVectorizer,lda,euclidean,-3.449040,-2.868100,-2.462440
16798,9492,15,dataset5,0.50,True,TfidfVectorizer,lda,euclidean,-0.029308,-0.329757,-2.469410
16799,16252,7,dataset9,0.05,True,NCutVectorizer,lda,euclidean,NaN,-2.714230,-2.586670

In [43]:
c5_df[c5_df['experiment_id'] == 8424]

,experiment_id,k,dataset,min_df,is_binary,vectorizer,method,distance,coherence_med5,coherence_med10,coherence_med15
153,8424,13,dataset5,0.05,True,CountVectorizer,lda,euclidean,0.003328,0.003328,0.003328

In [65]:
import math
from itertools import combinations
TOP = 0.01
total = c5_df.shape[0]
rows = math.ceil(total * TOP)
print(rows)
ids = {}
# ids['sil'] = set(sil_df['experiment_id'].head(rows).values.tolist())
ids['c5'] = set(c5_df['experiment_id'].head(rows).values.tolist())
ids['c10'] = set(c10_df['experiment_id'].head(rows).values.tolist())
ids['c15'] = set(c15_df['experiment_id'].head(rows).values.tolist())
# print(len(ids['sil']))
combs = combinations(ids.keys(), 2)
for comb in combs:
    print("Merge set for %s and %s" % comb)
    merge_ids = ids[comb[0]] & ids[comb[1]]
    print("Size: %d" % len(merge_ids))
    print("Ids: %s" % merge_ids)
    print()
    
combs = combinations(ids.keys(), 3)
for comb in combs:
    print("Merge set for %s, %s and %s" % comb)
    merge_ids = ids[comb[0]] & ids[comb[1]] & ids[comb[2]]
    print("Size: %d" % len(merge_ids))
    print("Ids: %s" % merge_ids)
    print()

168
Merge set for c5 and c10
Size: 168
Ids: {6657, 6659, 11272, 11787, 9741, 14, 9744, 11280, 12311, 27, 1564, 10270, 13855, 6178, 9763, 6180, 6182, 551, 2095, 11311, 6711, 6713, 13377, 6210, 13379, 6212, 16461, 1614, 1617, 1619, 6747, 4701, 6238, 8288, 11362, 7778, 3172, 16483, 7271, 12906, 8815, 4723, 13431, 13433, 6271, 1671, 1673, 12940, 8337, 8339, 13467, 11421, 1182, 13991, 1707, 3246, 15535, 11443, 7860, 2231, 7866, 188, 3775, 12991, 8391, 8393, 11470, 1231, 15057, 15059, 14036, 3297, 3299, 8424, 9962, 8427, 14572, 6381, 14576, 13046, 8951, 10495, 2816, 6403, 2822, 15111, 4872, 15113, 2826, 7950, 7951, 14100, 3351, 3353, 14620, 10017, 10019, 15142, 15144, 15146, 15147, 13101, 14640, 15671, 3384, 3387, 2876, 1341, 9534, 13123, 3911, 9544, 9548, 5455, 14671, 1363, 10071, 10073, 16732, 2911, 16737, 16739, 868, 9580, 4977, 4979, 16246, 10107, 8061, 9598, 16260, 10631, 4494, 12175, 8083, 13206, 16791, 16793, 415, 9631, 5031, 5033, 11697, 4530, 11699, 16310, 16314, 14781, 16324, 4552, 5067, 3021, 10192, 14803, 4564, 11222, 5591, 2526, 7135, 16351, 1506, 3043, 5090, 11751, 11753, 4591, 14836, 2044}

Merge set for c5 and c15
Size: 14
Ids: {10107, 8424, 15144, 11787, 13467, 1707, 14, 8427, 15147, 3387, 5067, 6747, 27, 10270}

Merge set for c10 and c15
Size: 14
Ids: {10107, 8424, 15144, 11787, 13467, 1707, 14, 8427, 15147, 3387, 5067, 6747, 27, 10270}

Merge set for c5, c10 and c15
Size: 14
Ids: {10107, 8424, 15144, 11787, 13467, 1707, 14, 8427, 15147, 3387, 5067, 6747, 27, 10270}

In [73]:
c5_df[(c5_df['min_df'] == 0.05) & (c5_df['k'] == 12)]

,experiment_id,k,dataset,min_df,is_binary,vectorizer,method,distance,coherence_med5,coherence_med10,coherence_med15
58,2822,12,dataset1,0.05,True,NCutVectorizer,lda,euclidean,0.004988,-0.161613,-0.198245
66,6182,12,dataset3,0.05,True,NCutVectorizer,lda,euclidean,0.004988,0.004988,-0.242389
69,6210,12,dataset3,0.05,False,NCutVectorizer,lda,euclidean,0.004988,-0.208818,-0.301111
70,4530,12,dataset2,0.05,False,NCutVectorizer,lda,euclidean,0.004988,0.004988,-0.373820
104,11222,12,dataset6,0.05,True,NCutVectorizer,lda,euclidean,0.004988,-0.120204,-1.510240
148,5090,12,dataset3,0.05,False,CountVectorizer,lda,euclidean,0.003742,-0.072387,-0.141878
167,15142,12,dataset9,0.05,True,CountVectorizer,lda,euclidean,0.003328,-0.038266,-0.109791
190,12902,12,dataset7,0.05,True,NCutVectorizer,lda,euclidean,0.003328,0.003328,-0.187307
394,9542,12,dataset5,0.05,True,NCutVectorizer,lda,euclidean,0.002598,-0.055691,-0.488447
414,5062,12,dataset3,0.05,True,CountVectorizer,lda,euclidean,0.002497,0.001998,-0.016571
428,21,12,dataset0,0.05,True,CountVectorizer,nmf,euclidean,0.002497,-0.017493,-0.044177
429,1701,12,dataset1,0.05,True,CountVectorizer,nmf,euclidean,0.002497,-0.017493,-0.044177
430,13461,12,dataset8,0.05,True,CountVectorizer,nmf,euclidean,0.002497,-0.017493,-0.044177
431,3381,12,dataset2,0.05,True,CountVectorizer,nmf,euclidean,0.002497,-0.017493,-0.044177
432,5061,12,dataset3,0.05,True,CountVectorizer,nmf,euclidean,0.002497,-0.017493,-0.044177
433,15141,12,dataset9,0.05,True,CountVectorizer,nmf,euclidean,0.002497,-0.017493,-0.044177
434,10101,12,dataset6,0.05,True,CountVectorizer,nmf,euclidean,0.002497,-0.017493,-0.044177
435,8421,12,dataset5,0.05,True,CountVectorizer,nmf,euclidean,0.002497,-0.017493,-0.044177
436,11781,12,dataset7,0.05,True,CountVectorizer,nmf,euclidean,0.002497,-0.017493,-0.044177
437,6741,12,dataset4,0.05,True,CountVectorizer,nmf,euclidean,0.002497,-0.017493,-0.044177
502,6742,12,dataset4,0.05,True,CountVectorizer,lda,euclidean,0.002497,-0.027893,-0.095926
536,12901,12,dataset7,0.05,True,NCutVectorizer,nmf,euclidean,0.002497,-0.051437,-0.108139
537,11221,12,dataset6,0.05,True,NCutVectorizer,nmf,euclidean,0.002497,-0.051437,-0.108139
538,4501,12,dataset2,0.05,True,NCutVectorizer,nmf,euclidean,0.002497,-0.051437,-0.108139
539,16261,12,dataset9,0.05,True,NCutVectorizer,nmf,euclidean,0.002497,-0.051437,-0.108139
540,7861,12,dataset4,0.05,True,NCutVectorizer,nmf,euclidean,0.002497,-0.051437,-0.108139
541,2821,12,dataset1,0.05,True,NCutVectorizer,nmf,euclidean,0.002497,-0.051437,-0.108139
542,9541,12,dataset5,0.05,True,NCutVectorizer,nmf,euclidean,0.002497,-0.051437,-0.108139
543,1141,12,dataset0,0.05,True,NCutVectorizer,nmf,euclidean,0.002497,-0.051437,-0.108139
544,6181,12,dataset3,0.05,True,NCutVectorizer,nmf,euclidean,0.002497,-0.051437,-0.108139
...,...,...,...,...,...,...,...,...,...,...,...
13048,16289,12,dataset9,0.05,False,NCutVectorizer,nmf,euclidean,-0.070849,-0.105850,-0.181469
13049,7889,12,dataset4,0.05,False,NCutVectorizer,nmf,euclidean,-0.070849,-0.105850,-0.181469
13050,12929,12,dataset7,0.05,False,NCutVectorizer,nmf,euclidean,-0.070849,-0.105850,-0.181469
13051,6209,12,dataset3,0.05,False,NCutVectorizer,nmf,euclidean,-0.070849,-0.105850,-0.181469
13052,14609,12,dataset8,0.05,False,NCutVectorizer,nmf,euclidean,-0.070849,-0.105850,-0.181469
13053,2849,12,dataset1,0.05,False,NCutVectorizer,nmf,euclidean,-0.070849,-0.105850,-0.181469
13313,11810,12,dataset7,0.05,False,CountVectorizer,lda,euclidean,-0.077101,-0.116364,-0.195775
13339,14050,12,dataset8,0.05,False,TfidfVectorizer,lda,euclidean,-0.077101,-0.194148,-0.433330
13346,3970,12,dataset2,0.05,False,TfidfVectorizer,lda,euclidean,-0.077101,-1.366300,-1.369160
13417,10130,12,dataset6,0.05,False,CountVectorizer,lda,euclidean,-0.079095,-0.118641,-0.216200
13506,9570,12,dataset5,0.05,False,NCutVectorizer,lda,euclidean,-0.080401,-0.339548,-0.604707
13890,1142,12,dataset0,0.05,True,NCutVectorizer,lda,euclidean,-0.090142,-0.126332,-0.213185
14241,15170,12,dataset9,0.05,False,CountVectorizer,lda,euclidean,-0.099635,-0.139765,-0.233871
14265,7330,12,dataset4,0.05,False,TfidfVectorizer,lda,euclidean,-0.100028,-0.181208,-0.607840
14517,7890,12,dataset4,0.05,False,NCutVectorizer,lda,euclidean,-0.106728,-0.249441,-0.348146
15121,12342,12,dataset7,0.05,True,TfidfVectorizer,lda,euclidean,-0.131655,-0.213398,-0.496688
15138,15702,12,dataset9,0.05,True,TfidfVectorizer,lda,euclidean,-0.131657,-0.764039,-1.540050
15846,15730,12,dataset9,0.05,False,TfidfVectorizer,lda,euclidean,-0.165253,-0.444832,-0.638514
15847,3942,12,dataset2,0.05,True,TfidfVectorizer,lda,euclidean,-0.165285,-0.201761,-0.428948
16047,582,12,dataset0,0.05,True,TfidfVectorizer,lda,euclidean,-0.174971,-0.186263,-0.583742
16104,10690,12,dataset6,0.05,False,TfidfVectorizer,lda,euclidean,-0.181043,-0.250669,-0.334903
16124,14022,12,dataset8,0.05,True,TfidfVectorizer,lda,euclidean,-0.185151,-0.196189,-0.421270
16265,14610,12,dataset8,0.05,False,NCutVectorizer,lda,euclidean,-0.204577,-0.339282,-0.497094
16366,2290,12,dataset1,0.05,False,TfidfVectorizer,lda,euclidean,-0.225475,-0.477776,-0.564713
16478,610,12,dataset0,0.05,False,TfidfVectorizer,lda,euclidean,-0.250731,-0.708563,-1.398970
16517,16262,12,dataset9,0.05,True,NCutVectorizer,lda,euclidean,-0.263178,-0.206677,-0.349066
16569,9010,12,dataset5,0.05,False,TfidfVectorizer,lda,euclidean,-0.282561,-0.210775,-0.979004
16593,12370,12,dataset7,0.05,False,TfidfVectorizer,lda,euclidean,-0.303565,-0.440334,-0.794870
16611,7302,12,dataset4,0.05,True,TfidfVectorizer,lda,euclidean,-0.328731,-0.915965,-1.131430
16768,5622,12,dataset3,0.05,True,TfidfVectorizer,lda,euclidean,-1.133160,-1.285050,-1.176620

In [1]:
## Cleaning database
last_id = 132
problems = Problem.objects.filter(id__gt=last_id)
# solutions_obj = Solution.objects.filter(problem__in=problems).update(ignore=True)
print("Problems to be ignored: %d" % problems.count())

problems = Problem.objects.filter(id__lte=last_id)
# problems = Problem.objects.all()
print("Problems to be used: %d" % problems.count())

solutions_obj = Solution.objects.filter(problem__in=problems, ignore=False).order_by('id')
# solutions_obj = Solution.objects.all().order_by('id')
print("Solutions to be used: %d" % solutions_obj.count())

docs_id = []
questions = []
solutions = []

# Fill separated structures
for sol in solutions_obj:
    docs_id.append(sol.id)
    questions.append(sol.problem.content)
    solutions.append(sol.content)

print("Got %d documents" %(solutions_obj.count()))

Problems to be ignored: 591
Problems to be used: 132
Solutions to be used: 54
Got 54 documents

In [29]:
def get_where_items(exp_id):
    cols = ["vectorizer", "min_df", "is_binary", "distance", "method", "dataset", "k", "model", "X"]
    query = "SELECT %s from EXPERIMENTS_STABILITY where experiment_id = %s" % (", ".join(cols), exp_id) 
    cursor.execute(query)
    where_items = cursor.fetchall()
    return where_items

def analyze(solutions, where_items, exp_id):
    v = eval(where_items[0][0])
    m = where_items[0][1]
    b = where_items[0][2]
    dist = where_items[0][3]
    method = where_items[0][4]
    k = where_items[0][6]
    model_db = pickle.loads(base64.b64decode(where_items[0][7]))
    X = np.asarray(where_items[0][8])

    train_data_features, vectorizer, feature_names = create_bag_of_words(solutions, v, binary=b, min_df=m)
    clustering = Clustering(train_data_features, k, metric=dist)
    clustering.seed = model_db.random_state
    
    model, document_topic, word_topic = getattr(clustering, method)()
    
#     savefig='problems_20190101_%s_%s_exp_%s_%s_document_topic_distribution' % (method, clustering.seed, 
#                                                                                    exp_id, clustering.k)
#     clustering.plot_topic_distribution(title="Topic distribution per document", ylabel="Document ID", savefig=savefig, cmap='Blues')

#     print("Count per class:")
#     clusters = clustering.document_topic.argmax(axis=1)
#     counts = np.unique(clusters, return_counts=True)
#     print(counts)
    return clustering, method, feature_names, model

In [30]:
from sklearn.feature_extraction.text import CountVectorizer
import pickle
import base64
import numpy as np
from tokenizer import create_bag_of_words
from clustering import Clustering


# Get experiment conditions
exp_id = 15142
where_items = get_where_items(exp_id)
print("Conditions")
print(where_items[0][0:7])

v = where_items[0][0]
m = where_items[0][1]
b = where_items[0][2]
dist = where_items[0][3]
method = where_items[0][4]
k = where_items[0][6]

query = "SELECT experiment_id from EXPERIMENTS_STABILITY where "
where_clause = [("vectorizer", v), ("min_df", m), ("is_binary", b), 
                ("distance", dist), ("method", method), ("k", k)]
query += " AND ".join(["%s = '%s'" % item for item in where_clause])
cursor.execute(query)
r = cursor.fetchall()

clusters = []

for exp_id in r:
    where_items = get_where_items(exp_id[0])
    print("Conditions")
    print(where_items[0][0:7])


    clustering, method, feature_names, model = analyze(solutions, where_items, exp_id)
    clusters.append(clustering.document_topic.argmax(axis=1))

Conditions
('CountVectorizer', 0.05, True, 'euclidean', 'lda', 'dataset9', 12)
Conditions
('CountVectorizer', 0.05, True, 'euclidean', 'lda', 'dataset0', 12)
Conditions
('CountVectorizer', 0.05, True, 'euclidean', 'lda', 'dataset1', 12)
Conditions
('CountVectorizer', 0.05, True, 'euclidean', 'lda', 'dataset2', 12)
Conditions
('CountVectorizer', 0.05, True, 'euclidean', 'lda', 'dataset3', 12)
Conditions
('CountVectorizer', 0.05, True, 'euclidean', 'lda', 'dataset4', 12)
Conditions
('CountVectorizer', 0.05, True, 'euclidean', 'lda', 'dataset5', 12)
Conditions
('CountVectorizer', 0.05, True, 'euclidean', 'lda', 'dataset6', 12)
Conditions
('CountVectorizer', 0.05, True, 'euclidean', 'lda', 'dataset7', 12)
Conditions
('CountVectorizer', 0.05, True, 'euclidean', 'lda', 'dataset8', 12)
Conditions
('CountVectorizer', 0.05, True, 'euclidean', 'lda', 'dataset9', 12)

In [31]:
clusters

[array([ 5,  5, 10,  5,  7,  5,  5,  1,  1,  1,  5,  1,  5,  0,  0,  1,  5,
         4,  7,  2,  4,  7,  7,  5,  7,  7, 10, 10,  4,  1,  4,  2,  0,  1,
         9,  1,  2,  0,  1,  5,  5,  5,  1,  1,  5,  5,  4,  9, 11, 11,  5,
         4,  2,  5]),
 array([ 0,  8,  2,  0,  0,  0,  0,  3,  3,  1,  2,  9, 11,  8,  7,  1,  2,
        11,  7,  0,  0,  7,  7,  2,  7,  7,  2,  2, 11,  9, 11, 11, 11,  1,
        10,  9, 10,  1,  1,  8,  8,  8,  1,  1, 11, 11, 10, 10,  4, 11,  8,
         8, 11,  0]),
 array([ 7, 10,  2,  7,  7,  7,  7, 11, 11,  7,  2,  7,  7, 11, 11,  7,  2,
        11,  8,  7,  7,  8,  8,  2,  8,  8,  2,  2, 11,  7, 11,  7,  7,  7,
         7,  7, 11,  7,  7, 10, 10, 11,  7,  0,  2,  2,  1,  1,  1, 10, 11,
        11,  2,  7]),
 array([10, 10,  3, 10, 10, 10, 10,  6,  6,  0,  3,  0, 10,  3,  6,  0,  7,
         3,  3,  9,  9,  2,  2,  3,  3,  2,  3,  3,  6,  0,  6,  9,  3,  0,
         0,  0,  9,  9,  0,  8,  8,  8,  0,  4,  1,  1,  0,  0,  9,  5,  8,
         9,  9, 10]),
 array([ 3, 11,  1,  3,  3,  3,  3,  0,  0,  0,  0,  0,  3,  0,  0,  0,  0,
         9,  3,  5, 10,  8,  8,  0,  3,  8,  0,  3,  3,  0,  3, 10,  0,  0,
         2,  0,  5,  5,  0, 11, 11, 11,  2,  2,  4,  4, 10,  2,  5,  5, 11,
        11, 10,  3]),
 array([2, 2, 8, 2, 2, 2, 2, 6, 6, 6, 1, 6, 2, 8, 6, 6, 1, 8, 7, 2, 2, 0,
        0, 1, 7, 0, 1, 1, 8, 6, 7, 3, 8, 6, 6, 6, 2, 6, 6, 1, 1, 1, 6, 6,
        3, 3, 5, 6, 5, 5, 1, 3, 2, 2]),
 array([ 0,  7,  4,  0,  0,  0,  0,  1,  1, 11,  6,  0,  0,  4,  1, 11,  2,
         4,  4,  0,  0,  1,  1,  6,  4,  1,  4,  4,  4,  0,  0,  0,  4, 11,
         0,  0,  0,  0, 11,  7,  7,  7,  7,  7,  0,  0,  0,  0,  0,  0,  4,
         0,  0,  0]),
 array([2, 2, 5, 9, 9, 9, 9, 8, 8, 8, 5, 8, 2, 2, 2, 8, 5, 5, 9, 8, 2, 3,
        3, 5, 9, 3, 5, 5, 2, 8, 2, 2, 2, 8, 4, 8, 2, 8, 8, 2, 2, 2, 8, 8,
        6, 6, 4, 4, 2, 8, 2, 2, 2, 2]),
 array([10, 11,  2,  2,  2,  2,  2,  8,  8,  1,  6,  9, 10,  9,  9,  1,  6,
         2,  2,  1, 11,  2,  2,  6,  2,  2,  6,  2,  2,  9,  2,  2,  9,  1,
         9,  9, 10,  1,  1, 11, 11, 10,  1,  1, 10, 10, 11,  9,  7, 10, 10,
        10, 10,  2]),
 array([ 6,  6,  8,  6,  6,  6,  6,  4,  4,  4,  8,  4,  6,  1,  1,  4,  8,
         0,  6,  1,  6,  5,  5,  8,  6,  5,  8,  6,  0,  4,  6,  1,  1,  4,
         1,  4,  1,  4,  4,  7,  7,  6,  4,  4,  2,  2,  1,  1,  1,  7,  6,
         1, 11,  6])]

In [50]:
from itertools import combinations
from sklearn.metrics.cluster import normalized_mutual_info_score


scores = []
ij = combinations(range(len(clusters)), 2)
for i, j in ij:
    scores.append(normalized_mutual_info_score(clusters[i], clusters[j], average_method='arithmetic'))

In [41]:
from scipy import stats
stats.describe(np.asarray(scores))

DescribeResult(nobs=45, minmax=(0.36006417231978466, 0.6798696013086902), mean=0.5361073319921684, variance=0.006867014084198572, skewness=-0.4436793753151618, kurtosis=-0.7683020197444734)

In [51]:
stats.describe(np.asarray(scores))

DescribeResult(nobs=45, minmax=(0.35750932735287044, 0.6786866711797224), mean=0.5345179878257761, variance=0.0068491350893785715, skewness=-0.4394407907629835, kurtosis=-0.7510573297358971)

In [52]:
scores = np.asarray(scores)
mean = scores.mean()
std = scores.std()
median = np.median(scores)
q75, q25 = np.percentile(scores, [75, 25])
iqr = q75 - q25

print(mean)
print(std)
print(median)
print(iqr)

0.5345179878257761
0.0818347853140239
0.5509299593872623
0.10702881637853245